-- Database initialization script for trpc-agent-service.
--
-- Role boundary: this is the GENESIS script — the 000001 baseline. It runs once
-- against an empty database, from three places: the postgres container
-- (/docker-entrypoint-initdb.d/), the k8s db-init Job, and CI.
--
-- It is frozen. Never edit the DDL below to change a schema that already
-- exists in some environment — that silently forks fresh databases from live
-- ones. Every change after this baseline is a numbered pair of files under
-- deploy/db/migrations/, applied by deploy/db/migrate.sh (golang-migrate).
--
-- The last block in this file stamps schema_migrations at version 1 so
-- `migrate up` resumes from 000002 instead of replaying the baseline.
-- Conventions and recovery steps: deploy/db/migrations/README.md.

-- pgvector: vector search for Knowledge.
CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- Tenant: base info and tenant-level policy config (JSONB carries dynamic
-- config, avoiding frequent DDL)
-- ---------------------------------------------------------------------------
CREATE TABLE tenant (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name           varchar(128) NOT NULL,
    model_config   jsonb,
    tool_policy    jsonb,
    audit_policy   jsonb,
    -- Guardrail policy (design 4.3 治理): input user allowlist, input/output
    -- deny words, daily token budget, e.g.
    -- {"input_allow_users":["u1"],"input_deny_words":["..."],"max_tokens_per_day":1000000}.
    guardrail_policy jsonb,
    -- Traffic admission policy for the gateway's per-tenant token bucket
    -- (design 5.1.4), e.g. {"qps": 50, "burst": 100}; empty means the
    -- platform default.
    rate_policy    jsonb,
    -- Data-backend overrides (a controlled menu), e.g.
    -- {"session":{"type":"redis","dsn_ref":"t42-redis"}}. Empty means the
    -- platform-recommended stack. Changes must go through the migration
    -- procedure; live switching is forbidden.
    storage_config jsonb,
    status         varchar(32) NOT NULL DEFAULT 'active',
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_tenant_status ON tenant (status);

-- ---------------------------------------------------------------------------
-- Agent app: per-tenant agent configuration, with versioning and gray release
-- ---------------------------------------------------------------------------
CREATE TABLE agent_app (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  uuid         NOT NULL REFERENCES tenant (id),
    name       varchar(128) NOT NULL,
    agent_type varchar(64)  NOT NULL,
    config     jsonb        NOT NULL, -- prompt, model and tool config
    version    int          NOT NULL,
    status     varchar(32)  NOT NULL DEFAULT 'draft', -- draft / published / disabled
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_agent_app_version UNIQUE (tenant_id, name, version)
);
-- At most one published version per (tenant, app name); publish/rollback is atomic.
CREATE UNIQUE INDEX uk_agent_app_published
    ON agent_app (tenant_id, name) WHERE status = 'published';
CREATE INDEX idx_agent_app_tenant ON agent_app (tenant_id);

-- ---------------------------------------------------------------------------
-- Channel binding: binds external channels to agent apps. Secrets are stored
-- as references only, never in plaintext.
-- ---------------------------------------------------------------------------
CREATE TABLE channel_binding (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid         NOT NULL REFERENCES tenant (id),
    channel      varchar(64)  NOT NULL, -- wecom / wechat_kf / mock ...
    app_id       uuid         NOT NULL REFERENCES agent_app (id),
    webhook_path varchar(256) NOT NULL,
    token_ref    varchar(256),          -- token secret reference; no plaintext
    aeskey_ref   varchar(256),          -- AES key secret reference; no plaintext
    -- Channel-specific config, e.g. wecom corp_id/agent_id; sensitive fields
    -- are still stored as references only.
    config       jsonb,
    status       varchar(32)  NOT NULL DEFAULT 'active',
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_channel_webhook UNIQUE (webhook_path) -- callback path is globally unique
);
CREATE INDEX idx_channel_binding_app ON channel_binding (app_id);
CREATE INDEX idx_channel_binding_tenant ON channel_binding (tenant_id, channel);

-- ---------------------------------------------------------------------------
-- Session: current state snapshot; full history lives in session_event.
-- session_key is generated by the Channel Adapter:
-- dm:{channel}:{user} / group:{channel}:{chat}
-- ---------------------------------------------------------------------------
CREATE TABLE session (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   uuid         NOT NULL,
    app_id      uuid         NOT NULL REFERENCES agent_app (id),
    session_key varchar(256) NOT NULL,
    user_id     varchar(128) NOT NULL,
    channel     varchar(64)  NOT NULL,
    state       jsonb        NOT NULL DEFAULT '{}', -- materialized snapshot; the event stream is the source of truth
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_session_app_key UNIQUE (app_id, session_key)
);
CREATE INDEX idx_session_user ON session (tenant_id, user_id);
CREATE INDEX idx_session_updated_at ON session (updated_at);

-- ---------------------------------------------------------------------------
-- Session event: append-only. UNIQUE (session_id, event_seq) guarantees
-- ordering without duplicates and doubles as the execution-layer idempotency
-- backstop for Stream redeliveries. Old rows are archived monthly; no
-- declarative partitioning.
-- ---------------------------------------------------------------------------
CREATE TABLE session_event (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id uuid        NOT NULL REFERENCES session (id),
    event_seq  bigint      NOT NULL,
    event      jsonb       NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_session_event_seq UNIQUE (session_id, event_seq)
);

-- ---------------------------------------------------------------------------
-- Memory item: app_id non-null = app-private, NULL = tenant-shared;
-- soft delete backs the "user asks to be forgotten" requirement.
-- ---------------------------------------------------------------------------
CREATE TABLE memory_item (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid         NOT NULL,
    app_id       uuid,                  -- NULL means tenant-shared memory
    user_id      varchar(128) NOT NULL,
    content      text         NOT NULL,
    topics       jsonb,                 -- framework memory topics (array of strings)
    embedding_id varchar(256),          -- vector ID in the vector store (externalized for easier migration)
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    deleted_at   timestamptz            -- NULL means active
);
CREATE INDEX idx_memory_item_user ON memory_item (tenant_id, user_id, app_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Memory embedding: vectors for memory semantic recall (design 5.1.3).
-- Written asynchronously by the memory embedding worker; memory_item stays
-- the source of truth and recall joins back by memory_id. The dimension must
-- equal TRPC_EMBEDDER_DIMENSION.
-- ---------------------------------------------------------------------------
CREATE TABLE memory_embedding (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    memory_id  uuid         NOT NULL UNIQUE REFERENCES memory_item (id) ON DELETE CASCADE,
    tenant_id  uuid         NOT NULL,
    embedding  vector(1536) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_memory_embedding_hnsw ON memory_embedding
    USING hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- Storage migration: one row per in-flight backend migration (design 5.2.6).
-- At most one active migration per (tenant, resource); terminal phases are
-- done / failed / aborted.
-- ---------------------------------------------------------------------------
CREATE TABLE storage_migration (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid         NOT NULL REFERENCES tenant (id),
    resource     varchar(32)  NOT NULL,  -- session (knowledge/artifact later)
    from_backend varchar(32)  NOT NULL,  -- redis / postgres
    to_backend   varchar(32)  NOT NULL,
    phase        varchar(32)  NOT NULL,  -- dual_write / backfilling / observing / done / failed / aborted
    progress     jsonb,                   -- sessions_total/done, cursor, mismatches, observe_until
    error        text,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_storage_migration_active
    ON storage_migration (tenant_id, resource) WHERE phase NOT IN ('done', 'failed', 'aborted');

-- ---------------------------------------------------------------------------
-- Summary: summary text + coverage cursor; crash recovery replays
-- incrementally from covered_event_id onward.
-- ---------------------------------------------------------------------------
CREATE TABLE summary (
    session_id       uuid PRIMARY KEY REFERENCES session (id),
    summary_text     text        NOT NULL,
    -- Logical reference without a foreign key: session_event rows get
    -- archived away, and a hard FK would block archival.
    covered_event_id uuid        NOT NULL,
    -- The framework event filter key the summary was built for (single-agent
    -- apps: the agent name). One row per session for now.
    filter_key       varchar(128) NOT NULL DEFAULT '',
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Audit log: routine events are written asynchronously in batches; critical
-- decisions (deny/review) are written synchronously (compliance red line).
-- Old rows are archived monthly into the same-shaped audit_log_archive.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid         NOT NULL,
    channel           varchar(64),
    user_id           varchar(128),
    session_id        uuid,
    agent_name        varchar(128),
    tool_name         varchar(128),
    decision          varchar(32)  NOT NULL, -- allow / deny / review / review_timeout
    latency_ms        int,
    error_type        varchar(64),
    cost              numeric(12, 6),
    prompt_tokens     int,
    completion_tokens int,
    trace_id          varchar(128),
    -- Admin write operations record the before/after payload here
    -- ({"before": ..., "after": ...}), design 5.4 变更审计.
    detail            jsonb,
    created_at        timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_tenant_time ON audit_log (tenant_id, created_at);
CREATE INDEX idx_audit_session ON audit_log (session_id);
CREATE INDEX idx_audit_trace ON audit_log (trace_id);

-- ---------------------------------------------------------------------------
-- Archive tables: same shape as their source tables (INSERT ... SELECT *),
-- but WITHOUT foreign keys — archived rows must not block or be blocked by
-- session deletion. The monthly archive task (storage.Archiver) copies old
-- rows here in limited batches, then deletes them from the source table.
-- ---------------------------------------------------------------------------
CREATE TABLE session_event_archive (
    id         uuid PRIMARY KEY,
    session_id uuid        NOT NULL,
    event_seq  bigint      NOT NULL,
    event      jsonb       NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT uk_session_event_archive_seq UNIQUE (session_id, event_seq)
);
CREATE INDEX idx_session_event_archive_created ON session_event_archive (created_at);

CREATE TABLE audit_log_archive (
    id                uuid PRIMARY KEY,
    tenant_id         uuid         NOT NULL,
    channel           varchar(64),
    user_id           varchar(128),
    session_id        uuid,
    agent_name        varchar(128),
    tool_name         varchar(128),
    decision          varchar(32)  NOT NULL,
    latency_ms        int,
    error_type        varchar(64),
    cost              numeric(12, 6),
    prompt_tokens     int,
    completion_tokens int,
    trace_id          varchar(128),
    detail            jsonb,
    created_at        timestamptz  NOT NULL
);
CREATE INDEX idx_audit_archive_tenant_time ON audit_log_archive (tenant_id, created_at);

-- ---------------------------------------------------------------------------
-- Migration bookkeeping
--
-- The genesis script above IS version 1, so stamp it. Without this row a
-- database created by compose, the db-init Job or CI looks un-migrated to
-- `migrate up`, which then starts counting from 0 with no idea the baseline
-- already ran.
--
-- Table shape is golang-migrate's postgres driver default: one row holding the
-- current version, not one row per applied migration. The guarded insert keeps
-- that invariant (and stays idempotent) rather than assuming an empty table.
-- Do not rename the table or its columns.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
    version bigint  NOT NULL PRIMARY KEY,
    dirty   boolean NOT NULL
);
INSERT INTO schema_migrations (version, dirty)
SELECT 1, false
WHERE NOT EXISTS (SELECT 1 FROM schema_migrations);
