package natsadapter

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"

	wire "github.com/liuzengh/trpc-agent-service/api/events/execution/v1"
	"github.com/nats-io/nats.go/jetstream"
	"gopkg.in/yaml.v3"
)

type StreamSpec struct {
	Retention       string `yaml:"retention"`
	Name            string `yaml:"name"`
	Subject         string `yaml:"subject"`
	MaxBytes        int64  `yaml:"max_bytes"`
	MaxMessageBytes int32  `yaml:"max_message_bytes"`
	Replicas        int    `yaml:"replicas"`
}
type Topology struct {
	Version int          `yaml:"version"`
	Streams []StreamSpec `yaml:"streams"`
}

func strictYAML(path string, out any) error {
	f, err := os.Open(path)
	if err != nil {
		return errors.New("open NATS declaration failed")
	}
	defer f.Close()
	b, err := io.ReadAll(io.LimitReader(f, 65537))
	if err != nil || len(b) > 65536 {
		return errors.New("NATS declaration exceeds limit")
	}
	d := yaml.NewDecoder(bytes.NewReader(b))
	d.KnownFields(true)
	if err = d.Decode(out); err != nil {
		return errors.New("invalid NATS declaration")
	}
	var extra any
	if d.Decode(&extra) != io.EOF {
		return errors.New("multiple NATS declarations")
	}
	return nil
}
func LoadTopology(path string) (Topology, error) {
	var t Topology
	if err := strictYAML(path, &t); err != nil {
		return t, err
	}
	return t, t.Validate()
}
func (t Topology) Validate() error {
	if t.Version != 1 || (len(t.Streams) < 2 || len(t.Streams) > 4) {
		return errors.New("topology version 1 requires Route/Run and optional Manifest/Reply streams")
	}
	seen := map[string]bool{}
	for _, s := range t.Streams {
		wantRetention := map[string]string{RouteStream: "limits", RunStream: "workqueue", ManifestStream: "limits", ReplyStream: "workqueue"}[s.Name]
		if s.Retention != wantRetention {
			return errors.New("invalid stream retention contract")
		}
		subject := map[string]string{RouteStream: RouteSubject, RunStream: RunSubject, ManifestStream: ManifestSubject, ReplyStream: ReplySubject}[s.Name]
		if subject == "" || s.Subject != subject || seen[s.Name] || s.MaxBytes < 1<<20 || s.MaxBytes > 1<<40 || s.MaxMessageBytes < 16384 || s.MaxMessageBytes > 1<<20 || (s.Replicas != 1 && s.Replicas != 3 && s.Replicas != 5) {
			return errors.New("invalid stream declaration")
		}
		// Admission may persist any schema-valid RunRequested. A smaller broker
		// limit would create permanently unpublishable Outbox work.
		if s.Name == RunStream && s.MaxMessageBytes < wire.MaxRunRequestedBytes {
			return errors.New("Run stream must fit the execution wire size contract")
		}
		if (s.Name == ReplyStream && s.MaxMessageBytes < wire.MaxReplyIntentBytes) || (s.Name == ManifestStream && s.MaxMessageBytes < 1<<20) {
			return errors.New("runtime stream must fit wire contract")
		}
		seen[s.Name] = true
	}
	if !seen[RouteStream] || !seen[RunStream] {
		return errors.New("Route and Run streams are required")
	}
	return nil
}
func (t Topology) HasStream(name string) bool {
	for _, s := range t.Streams {
		if s.Name == name {
			return true
		}
	}
	return false
}
func (t Topology) configs() []jetstream.StreamConfig {
	var out []jetstream.StreamConfig
	for _, s := range t.Streams {
		policy := jetstream.LimitsPolicy
		if s.Retention == "workqueue" {
			policy = jetstream.WorkQueuePolicy
		}
		out = append(out, jetstream.StreamConfig{Name: s.Name, Subjects: []string{s.Subject}, Storage: jetstream.FileStorage, Retention: policy, MaxBytes: s.MaxBytes, MaxMsgSize: s.MaxMessageBytes, MaxMsgs: -1, MaxMsgsPerSubject: -1, Discard: jetstream.DiscardNew, Replicas: s.Replicas, Duplicates: 2 * time.Minute, DenyDelete: true, DenyPurge: true})
	}
	return out
}

type Role struct {
	User        string   `yaml:"user"`
	PasswordEnv string   `yaml:"password_env"`
	Publish     []string `yaml:"publish"`
	Subscribe   []string `yaml:"subscribe"`
}
type Permissions struct {
	Version int    `yaml:"version"`
	Roles   []Role `yaml:"roles"`
}

// RenderServerConfig emits only public declarations and environment references.
// Secrets are resolved by nats-server, never rendered by this command.
func RenderServerConfig(path string) ([]byte, error) {
	var p Permissions
	if err := strictYAML(path, &p); err != nil {
		return nil, err
	}
	if p.Version != 1 || len(p.Roles) == 0 {
		return nil, errors.New("invalid NATS permission version")
	}
	var b strings.Builder
	b.WriteString("# Generated by channel-gateway nats-config; do not edit.\nport: 4222\njetstream { store_dir: /data/jetstream }\nauthorization {\n  users: [\n")
	sort.Slice(p.Roles, func(i, j int) bool { return p.Roles[i].User < p.Roles[j].User })
	seen := map[string]bool{}
	for _, r := range p.Roles {
		if !regexp.MustCompile(`^[a-z][a-z0-9_-]{0,63}$`).MatchString(r.User) || seen[r.User] || !regexp.MustCompile(`^NATS_[A-Z0-9_]+_PASSWORD$`).MatchString(r.PasswordEnv) || len(r.Publish) == 0 || len(r.Subscribe) == 0 {
			return nil, errors.New("invalid NATS role")
		}
		seen[r.User] = true
		b.WriteString(fmt.Sprintf("    { user: %q, password: $%s, permissions: {\n", r.User, r.PasswordEnv))
		for _, list := range []struct {
			name   string
			values []string
		}{{"publish", r.Publish}, {"subscribe", r.Subscribe}} {
			b.WriteString("      " + list.name + ": [")
			for i, s := range list.values {
				if strings.ContainsAny(s, "\"\\\r\n\t ") || s == "" {
					return nil, errors.New("invalid permission subject")
				}
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(fmt.Sprintf("%q", s))
			}
			b.WriteString("]\n")
		}
		b.WriteString("    } },\n")
	}
	b.WriteString("  ]\n}\n")
	return []byte(b.String()), nil
}
