// Package app defines the tenant-scoped application and publication lifecycle.
package app

import (
	"crypto/rand"
	"errors"
	"fmt"
	"math/big"
	"strings"
	"time"
)

// Status is the lifecycle state of an Agent App.
type Status string

const (
	// StatusDraft identifies an App that has no published revision.
	StatusDraft Status = "draft"
	// StatusActive identifies an App that may accept new executions.
	StatusActive Status = "active"
	// StatusSuspended rejects new executions while preserving published state.
	StatusSuspended Status = "suspended"
	// StatusDisabled is the terminal App lifecycle state.
	StatusDisabled Status = "disabled"
)

var (
	// ErrInvalid reports malformed Agent App domain state or input.
	ErrInvalid = errors.New("invalid agent app")
	// ErrNotFound reports that an Agent App or revision does not exist in scope.
	ErrNotFound = errors.New("agent app not found")
	// ErrConflict reports an optimistic-lock conflict.
	ErrConflict = errors.New("agent app version conflict")
	// ErrDuplicateKey reports an App key collision inside one tenant.
	ErrDuplicateKey = errors.New("agent app key already exists")
	// ErrDisabled reports an operation rejected by the terminal state.
	ErrDisabled = errors.New("agent app is disabled")
	// ErrInvalidTransition reports an unsupported lifecycle transition.
	ErrInvalidTransition = errors.New("invalid agent app status transition")
	// ErrImmutableRevision reports an attempted change to published content.
	ErrImmutableRevision = errors.New("published agent app revision is immutable")
)

// App is the stable tenant-scoped identity and publication pointer for an
// Agent application. Executable configuration belongs to Revision.
type App struct {
	TenantID        string
	AppID           string
	AppKey          string
	DisplayName     string
	Description     string
	Status          Status
	CurrentRevision *int64
	CanaryRevision  *int64
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// CreateInput contains the caller-selected fields for a new App. AppID is
// generated by the service and new Apps always begin in draft state.
type CreateInput struct {
	TenantID    string
	AppKey      string
	DisplayName string
	Description string
}

// NewApp validates input and constructs a new draft App.
func NewApp(input CreateInput) (*App, error) {
	if err := validateTenantID(input.TenantID); err != nil {
		return nil, err
	}
	key, err := normalizeAppKey(input.AppKey)
	if err != nil {
		return nil, err
	}
	if err := validateAppMetadata(input.DisplayName, input.Description); err != nil {
		return nil, err
	}
	id, err := newAppID()
	if err != nil {
		return nil, fmt.Errorf("generate agent app id: %w", err)
	}
	now := time.Now().UTC()
	return &App{
		TenantID:    input.TenantID,
		AppID:       id,
		AppKey:      key,
		DisplayName: strings.TrimSpace(input.DisplayName),
		Description: strings.TrimSpace(input.Description),
		Status:      StatusDraft,
		Version:     1,
		CreatedAt:   now,
		UpdatedAt:   now,
	}, nil
}

// Clone returns a defensive copy suitable for repository and snapshot
// boundaries.
func (a App) Clone() App {
	clone := a
	clone.CurrentRevision = cloneInt64(a.CurrentRevision)
	clone.CanaryRevision = cloneInt64(a.CanaryRevision)
	return clone
}

// Validate checks the complete App root invariants, including normalized
// identity, lifecycle-to-publication consistency, version, and timestamps.
func (a App) Validate() error {
	if err := a.validateIdentity(); err != nil {
		return err
	}
	if err := a.validateLifecycle(); err != nil {
		return err
	}
	if a.Version < 1 || a.CreatedAt.IsZero() || a.UpdatedAt.IsZero() || a.UpdatedAt.Before(a.CreatedAt) {
		return fmt.Errorf("%w: version and timestamps must be initialized and ordered", ErrInvalid)
	}
	return nil
}

func (a App) validateIdentity() error {
	if err := validateTenantID(a.TenantID); err != nil {
		return err
	}
	if err := validateAppID(a.AppID); err != nil {
		return err
	}
	key, err := normalizeAppKey(a.AppKey)
	if err != nil {
		return err
	}
	if key != a.AppKey {
		return fmt.Errorf("%w: app key must be normalized", ErrInvalid)
	}
	if err := validateAppMetadata(a.DisplayName, a.Description); err != nil {
		return err
	}
	if a.DisplayName != strings.TrimSpace(a.DisplayName) || a.Description != strings.TrimSpace(a.Description) {
		return fmt.Errorf("%w: app metadata must be normalized", ErrInvalid)
	}
	return nil
}

func (a App) validateLifecycle() error {
	if !validStatus(a.Status) {
		return fmt.Errorf("%w: unknown status %q", ErrInvalid, a.Status)
	}
	switch a.Status {
	case StatusDraft:
		if a.CurrentRevision != nil {
			return fmt.Errorf("%w: draft app cannot select a published revision", ErrInvalid)
		}
	case StatusActive, StatusSuspended:
		if a.CurrentRevision == nil || *a.CurrentRevision < 1 {
			return fmt.Errorf("%w: %s app requires a current revision", ErrInvalid, a.Status)
		}
	case StatusDisabled:
		if a.CurrentRevision != nil && *a.CurrentRevision < 1 {
			return fmt.Errorf("%w: current revision must be positive", ErrInvalid)
		}
	}
	if a.CanaryRevision != nil && (*a.CanaryRevision < 1 || a.CurrentRevision == nil || *a.CanaryRevision == *a.CurrentRevision) {
		return fmt.Errorf("%w: canary revision must be positive and differ from current revision", ErrInvalid)
	}
	return nil
}

// CanAcceptExecution reports whether the App root can admit a new execution.
// The selected Revision and Tenant still require independent validation.
func (a App) CanAcceptExecution() bool {
	return a.Status == StatusActive && a.CurrentRevision != nil && *a.CurrentRevision >= 1
}

// CanTransitionTo reports whether a control-plane lifecycle transition is
// allowed. First publication promotes draft to active outside this state
// transition operation.
func (a App) CanTransitionTo(next Status) bool {
	switch a.Status {
	case StatusDraft:
		return next == StatusDisabled
	case StatusActive:
		return next == StatusSuspended || next == StatusDisabled
	case StatusSuspended:
		return next == StatusActive || next == StatusDisabled
	default:
		return false
	}
}

func validStatus(status Status) bool {
	return status == StatusDraft || status == StatusActive || status == StatusSuspended || status == StatusDisabled
}

func validateAppMetadata(displayName, description string) error {
	if n := len([]rune(strings.TrimSpace(displayName))); n < 1 || n > 200 {
		return fmt.Errorf("%w: display name must contain 1-200 characters", ErrInvalid)
	}
	if len([]rune(strings.TrimSpace(description))) > 2000 {
		return fmt.Errorf("%w: description must contain at most 2000 characters", ErrInvalid)
	}
	return nil
}

func normalizeAppKey(key string) (string, error) {
	key = strings.ToLower(strings.TrimSpace(key))
	if len(key) < 2 || len(key) > 64 || key[0] < 'a' || key[0] > 'z' {
		return "", fmt.Errorf("%w: app key must match [a-z][a-z0-9-]{1,63}", ErrInvalid)
	}
	for i := 1; i < len(key); i++ {
		c := key[i]
		if (c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '-' {
			return "", fmt.Errorf("%w: app key must match [a-z][a-z0-9-]{1,63}", ErrInvalid)
		}
	}
	return key, nil
}

func validateTenantID(id string) error {
	return validateCrockfordID(id, "t_", "tenant")
}

func validateAppID(id string) error {
	return validateCrockfordID(id, "app_", "agent app")
}

func validateCrockfordID(id, prefix, label string) error {
	payload := strings.TrimPrefix(id, prefix)
	if payload == id || len(payload) != 26 {
		return fmt.Errorf("%w: %s id must be %s followed by 26 Crockford characters", ErrInvalid, label, prefix)
	}
	if payload[0] > '7' {
		return fmt.Errorf("%w: %s id has invalid ULID padding bits", ErrInvalid, label)
	}
	for _, c := range payload {
		if !strings.ContainsRune("0123456789ABCDEFGHJKMNPQRSTVWXYZ", c) {
			return fmt.Errorf("%w: invalid %s id", ErrInvalid, label)
		}
	}
	return nil
}

const crockfordAlphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

func newAppID() (string, error) {
	var data [16]byte
	milliseconds := time.Now().UnixMilli()
	for i := 5; i >= 0; i-- {
		data[i] = byte(milliseconds)
		milliseconds >>= 8
	}
	if _, err := rand.Read(data[6:]); err != nil {
		return "", err
	}
	value := new(big.Int).SetBytes(data[:])
	var encoded [26]byte
	for i := len(encoded) - 1; i >= 0; i-- {
		encoded[i] = crockfordAlphabet[value.Uint64()&31]
		value.Rsh(value, 5)
	}
	return "app_" + string(encoded[:]), nil
}

func cloneInt64(value *int64) *int64 {
	if value == nil {
		return nil
	}
	clone := *value
	return &clone
}
