apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trpc-agent
resources:
  - job.yaml
images:
  - name: trpc-agent-service
    newName: trpc-agent-service
    newTag: replace-me
