apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trpc-agent
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - model.yaml
  - collector.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: trpc-agent-kubernetes-demo
    includeSelectors: false
