FROM golang:1.25-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /out/e2e-worker ./cmd/e2e-worker

FROM alpine:3.20

RUN apk add --no-cache ca-certificates wget \
    && addgroup -S trpc \
    && adduser -S -G trpc trpc

COPY --from=build /out/e2e-worker /usr/local/bin/e2e-worker

USER trpc

ENTRYPOINT ["/usr/local/bin/e2e-worker"]
