// Package backend models tenant-scoped data backend selection without
// resolving credentials or constructing runtime clients.
package backend

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"hash"
	"math/big"
	"net"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
)

const (
	currentSchemaVersion = 1
	maxEndpointLength    = 2048
	maxOptionValueLength = 4096
	maxSecretRefLength   = 256
)

// Status is the lifecycle state of a Backend Profile.
type Status string

const (
	// StatusActive identifies a Profile that may admit new executions.
	StatusActive Status = "active"
	// StatusSuspended rejects new executions while remaining configurable.
	StatusSuspended Status = "suspended"
	// StatusDisabled is the terminal Profile lifecycle state.
	StatusDisabled Status = "disabled"
)

// Capability identifies one data responsibility selected by a Profile.
type Capability string

const (
	// CapabilitySession permits session-aware backend execution.
	CapabilitySession Capability = "session"
	// CapabilityMemory permits memory-aware backend execution.
	CapabilityMemory Capability = "memory"
	// CapabilitySummary permits summary-aware backend execution.
	CapabilitySummary Capability = "summary"
	// CapabilityKnowledge permits knowledge-aware backend execution.
	CapabilityKnowledge Capability = "knowledge"
	// CapabilityArtifact permits artifact-aware backend execution.
	CapabilityArtifact Capability = "artifact"
	// CapabilityAudit permits audit-aware backend execution.
	CapabilityAudit Capability = "audit"
)

var (
	// ErrInvalid reports malformed Backend Profile state or input.
	ErrInvalid = errors.New("invalid backend profile")
	// ErrNotFound reports that a Profile does not exist in the requested scope.
	ErrNotFound = errors.New("backend profile not found")
	// ErrConflict reports an optimistic-lock conflict.
	ErrConflict = errors.New("backend profile version conflict")
	// ErrDuplicateKey reports a Profile key collision inside one tenant.
	ErrDuplicateKey = errors.New("backend profile key already exists")
	// ErrDisabled reports an operation rejected by the terminal state.
	ErrDisabled = errors.New("backend profile is disabled")
	// ErrInvalidTransition reports an unsupported lifecycle transition.
	ErrInvalidTransition = errors.New("invalid backend profile status transition")
)

// CapabilityBinding is normalized, secret-free control-plane configuration
// for one data capability. SecretRef is an opaque reference, never a value.
type CapabilityBinding struct {
	Capability Capability
	Provider   string
	Endpoint   string
	Options    map[string]string
	SecretRef  string
}

// Clone returns a defensive copy of a capability binding.
func (b CapabilityBinding) Clone() CapabilityBinding {
	clone := b
	clone.Options = cloneStringMap(b.Options)
	return clone
}

// Profile is the stable tenant-scoped Backend Profile root.
type Profile struct {
	TenantID      string
	ProfileID     string
	ProfileKey    string
	DisplayName   string
	Description   string
	Status        Status
	SchemaVersion int
	Bindings      []CapabilityBinding
	ContentDigest string
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// CreateInput contains the caller-selected fields for a new Profile.
// ProfileID is always generated by the service.
type CreateInput struct {
	TenantID      string
	ProfileKey    string
	DisplayName   string
	Description   string
	Status        Status
	SchemaVersion int
	Bindings      []CapabilityBinding
	Metadata      ChangeMetadata
}

// NewProfile validates, normalizes, and constructs a Backend Profile.
func NewProfile(input CreateInput, catalog *ProviderCatalog) (*Profile, error) {
	if err := validateTenantID(input.TenantID); err != nil {
		return nil, err
	}
	key, err := normalizeProfileKey(input.ProfileKey)
	if err != nil {
		return nil, err
	}
	displayName, description, err := normalizeMetadata(input.DisplayName, input.Description)
	if err != nil {
		return nil, err
	}
	status := input.Status
	if status == "" {
		status = StatusActive
	}
	if status != StatusActive && status != StatusSuspended {
		if status == StatusDisabled {
			return nil, fmt.Errorf("%w: new profile cannot be disabled", ErrInvalid)
		}
		return nil, fmt.Errorf("%w: unknown status %q", ErrInvalid, status)
	}
	schemaVersion := input.SchemaVersion
	if schemaVersion == 0 {
		schemaVersion = currentSchemaVersion
	}
	bindings, digest, err := normalizeConfiguration(schemaVersion, input.Bindings, catalog)
	if err != nil {
		return nil, err
	}
	if err := validateLifecycleConfiguration(status, bindings); err != nil {
		return nil, err
	}
	id, err := newProfileID()
	if err != nil {
		return nil, fmt.Errorf("generate backend profile id: %w", err)
	}
	now := time.Now().UTC()
	return &Profile{
		TenantID: input.TenantID, ProfileID: id, ProfileKey: key,
		DisplayName: displayName, Description: description, Status: status,
		SchemaVersion: schemaVersion, Bindings: bindings, ContentDigest: digest,
		Version: 1, CreatedAt: now, UpdatedAt: now,
	}, nil
}

// Clone returns a defensive copy suitable for repository and snapshot
// boundaries.
func (p Profile) Clone() Profile {
	clone := p
	clone.Bindings = cloneBindings(p.Bindings)
	return clone
}

// Validate checks the complete Profile invariants against the same trusted
// provider catalog used when the configuration was accepted.
func (p Profile) Validate(catalog *ProviderCatalog) error {
	if err := validateTenantID(p.TenantID); err != nil {
		return err
	}
	if err := validateProfileID(p.ProfileID); err != nil {
		return err
	}
	key, err := normalizeProfileKey(p.ProfileKey)
	if err != nil {
		return err
	}
	if key != p.ProfileKey {
		return fmt.Errorf("%w: profile key must be normalized", ErrInvalid)
	}
	displayName, description, err := normalizeMetadata(p.DisplayName, p.Description)
	if err != nil {
		return err
	}
	if displayName != p.DisplayName || description != p.Description {
		return fmt.Errorf("%w: profile metadata must be normalized", ErrInvalid)
	}
	if !validStatus(p.Status) {
		return fmt.Errorf("%w: unknown status %q", ErrInvalid, p.Status)
	}
	bindings, digest, err := normalizeConfiguration(p.SchemaVersion, p.Bindings, catalog)
	if err != nil {
		return err
	}
	if !bindingsEqual(bindings, p.Bindings) {
		return fmt.Errorf("%w: capability bindings must be normalized", ErrInvalid)
	}
	if err := validateLifecycleConfiguration(p.Status, bindings); err != nil {
		return err
	}
	if p.ContentDigest != digest {
		return fmt.Errorf("%w: content digest does not match configuration", ErrInvalid)
	}
	if p.Version < 1 || p.CreatedAt.IsZero() || p.UpdatedAt.IsZero() || p.UpdatedAt.Before(p.CreatedAt) ||
		p.CreatedAt.Location() != time.UTC || p.UpdatedAt.Location() != time.UTC {
		return fmt.Errorf("%w: version and timestamps must be initialized, UTC, and ordered", ErrInvalid)
	}
	return nil
}

// CanAcceptExecution reports whether the Profile lifecycle can admit a new
// execution. Snapshot construction still validates Tenant selection and all
// Profile invariants.
func (p Profile) CanAcceptExecution() bool {
	return p.Status == StatusActive && hasCapability(p.Bindings, CapabilitySession)
}

// CanTransitionTo reports whether a lifecycle transition is allowed.
func (p Profile) CanTransitionTo(next Status) bool {
	switch p.Status {
	case StatusActive:
		return next == StatusSuspended || next == StatusDisabled
	case StatusSuspended:
		return next == StatusActive || next == StatusDisabled
	default:
		return false
	}
}

func normalizeConfiguration(schemaVersion int, bindings []CapabilityBinding, catalog *ProviderCatalog) ([]CapabilityBinding, string, error) {
	if schemaVersion != currentSchemaVersion {
		return nil, "", fmt.Errorf("%w: unsupported schema version", ErrInvalid)
	}
	if catalog == nil {
		return nil, "", fmt.Errorf("%w: provider catalog is required", ErrInvalid)
	}
	normalized, err := catalog.NormalizeBindings(bindings)
	if err != nil {
		return nil, "", err
	}
	return normalized, contentDigest(schemaVersion, normalized), nil
}

func validateLifecycleConfiguration(status Status, bindings []CapabilityBinding) error {
	if status != StatusDisabled && len(bindings) == 0 {
		return fmt.Errorf("%w: non-disabled profile requires at least one capability binding", ErrInvalid)
	}
	if status == StatusActive && !hasCapability(bindings, CapabilitySession) {
		return fmt.Errorf("%w: active profile requires a session binding", ErrInvalid)
	}
	return nil
}

func hasCapability(bindings []CapabilityBinding, capability Capability) bool {
	for _, binding := range bindings {
		if binding.Capability == capability {
			return true
		}
	}
	return false
}

func validStatus(status Status) bool {
	return status == StatusActive || status == StatusSuspended || status == StatusDisabled
}

func validCapability(capability Capability) bool {
	switch capability {
	case CapabilitySession, CapabilityMemory, CapabilitySummary, CapabilityKnowledge, CapabilityArtifact, CapabilityAudit:
		return true
	default:
		return false
	}
}

func capabilityRank(capability Capability) int {
	switch capability {
	case CapabilitySession:
		return 0
	case CapabilityMemory:
		return 1
	case CapabilitySummary:
		return 2
	case CapabilityKnowledge:
		return 3
	case CapabilityArtifact:
		return 4
	case CapabilityAudit:
		return 5
	default:
		return 6
	}
}

func normalizeMetadata(displayName, description string) (string, string, error) {
	displayName = strings.TrimSpace(displayName)
	description = strings.TrimSpace(description)
	if n := len([]rune(displayName)); n < 1 || n > 200 {
		return "", "", fmt.Errorf("%w: display name must contain 1-200 characters", ErrInvalid)
	}
	if len([]rune(description)) > 2000 {
		return "", "", fmt.Errorf("%w: description must not exceed 2000 characters", ErrInvalid)
	}
	return displayName, description, nil
}

func normalizeProfileKey(key string) (string, error) {
	key = strings.ToLower(strings.TrimSpace(key))
	if len(key) < 2 || len(key) > 64 || key[0] < 'a' || key[0] > 'z' {
		return "", fmt.Errorf("%w: profile key must match [a-z][a-z0-9-]{1,63}", ErrInvalid)
	}
	for i := 1; i < len(key); i++ {
		c := key[i]
		if (c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '-' {
			return "", fmt.Errorf("%w: profile key must match [a-z][a-z0-9-]{1,63}", ErrInvalid)
		}
	}
	return key, nil
}

// FieldPolicy controls whether a provider field is accepted.
type FieldPolicy string

const (
	// FieldForbidden prevents a backend field from being configured.
	FieldForbidden FieldPolicy = "forbidden"
	// FieldOptional permits callers to omit a backend field.
	FieldOptional FieldPolicy = "optional"
	// FieldRequired requires callers to configure a backend field.
	FieldRequired FieldPolicy = "required"
)

// OptionKind controls normalization of an allowlisted provider option.
type OptionKind string

const (
	// OptionString identifies a string-valued backend option.
	OptionString OptionKind = "string"
	// OptionBoolean identifies a boolean-valued backend option.
	OptionBoolean OptionKind = "boolean"
	// OptionInteger identifies an integer-valued backend option.
	OptionInteger OptionKind = "integer"
	// OptionEnum identifies an enumerated backend option.
	OptionEnum OptionKind = "enum"
)

// OptionSpec is the trusted schema for one non-secret provider option.
type OptionSpec struct {
	Kind          OptionKind
	Required      bool
	DefaultValue  *string
	AllowedValues []string
	MinInteger    *int64
	MaxInteger    *int64
}

// ProviderSpec declares one trusted provider and its accepted control-plane
// configuration. It registers the provider for every listed capability.
type ProviderSpec struct {
	Provider        string
	Capabilities    []Capability
	EndpointPolicy  FieldPolicy
	EndpointSchemes []string
	SecretRefPolicy FieldPolicy
	Options         map[string]OptionSpec
	// ValidateBinding optionally applies provider-specific validation to a
	// normalized, secret-free capability binding.
	ValidateBinding func(CapabilityBinding) bool
}

type compiledProviderSpec struct {
	provider        string
	endpointPolicy  FieldPolicy
	endpointSchemes map[string]struct{}
	secretRefPolicy FieldPolicy
	options         map[string]OptionSpec
	validateBinding func(CapabilityBinding) bool
}

// ProviderCatalog is an immutable trusted registry used to reject unknown
// provider configuration before it can enter a runtime snapshot.
type ProviderCatalog struct {
	providers map[Capability]map[string]compiledProviderSpec
}

// NewProviderCatalog validates and defensively copies trusted provider specs.
func NewProviderCatalog(specs ...ProviderSpec) (*ProviderCatalog, error) {
	catalog := &ProviderCatalog{providers: make(map[Capability]map[string]compiledProviderSpec)}
	if len(specs) == 0 {
		return nil, fmt.Errorf("%w: provider catalog cannot be empty", ErrInvalid)
	}
	for _, spec := range specs {
		compiled, capabilities, err := compileProviderSpec(spec)
		if err != nil {
			return nil, err
		}
		for _, capability := range capabilities {
			byProvider := catalog.providers[capability]
			if byProvider == nil {
				byProvider = make(map[string]compiledProviderSpec)
				catalog.providers[capability] = byProvider
			}
			if _, exists := byProvider[compiled.provider]; exists {
				return nil, fmt.Errorf("%w: duplicate provider schema for capability %q", ErrInvalid, capability)
			}
			byProvider[compiled.provider] = compiled
		}
	}
	return catalog, nil
}

// NormalizeBindings validates and returns a canonical defensive copy sorted by
// capability. Unknown providers, fields, and duplicate capabilities fail.
func (c *ProviderCatalog) NormalizeBindings(bindings []CapabilityBinding) ([]CapabilityBinding, error) {
	if c == nil || len(c.providers) == 0 {
		return nil, fmt.Errorf("%w: provider catalog is required", ErrInvalid)
	}
	result := make([]CapabilityBinding, 0, len(bindings))
	seen := make(map[Capability]struct{}, len(bindings))
	for _, binding := range bindings {
		if !validCapability(binding.Capability) {
			return nil, fmt.Errorf("%w: unknown capability", ErrInvalid)
		}
		if _, exists := seen[binding.Capability]; exists {
			return nil, fmt.Errorf("%w: duplicate capability %q", ErrInvalid, binding.Capability)
		}
		seen[binding.Capability] = struct{}{}
		provider := strings.ToLower(strings.TrimSpace(binding.Provider))
		if !validProviderName(provider) {
			return nil, fmt.Errorf("%w: invalid provider name", ErrInvalid)
		}
		spec, exists := c.providers[binding.Capability][provider]
		if !exists {
			return nil, fmt.Errorf("%w: provider is not registered for capability %q", ErrInvalid, binding.Capability)
		}
		normalized, err := spec.normalizeBinding(binding.Capability, binding.Endpoint, binding.Options, binding.SecretRef)
		if err != nil {
			return nil, err
		}
		result = append(result, normalized)
	}
	sort.Slice(result, func(i, j int) bool {
		return capabilityRank(result[i].Capability) < capabilityRank(result[j].Capability)
	})
	return result, nil
}

func compileProviderSpec(spec ProviderSpec) (compiledProviderSpec, []Capability, error) {
	provider, err := compileProviderName(spec.Provider)
	if err != nil {
		return compiledProviderSpec{}, nil, err
	}
	capabilities, err := compileCapabilities(spec.Capabilities)
	if err != nil {
		return compiledProviderSpec{}, nil, err
	}
	schemes, err := compileEndpointSchema(spec.EndpointPolicy, spec.SecretRefPolicy, spec.EndpointSchemes)
	if err != nil {
		return compiledProviderSpec{}, nil, err
	}
	options, err := compileProviderOptions(spec.Options)
	if err != nil {
		return compiledProviderSpec{}, nil, err
	}
	return compiledProviderSpec{
		provider: provider, endpointPolicy: spec.EndpointPolicy, endpointSchemes: schemes,
		secretRefPolicy: spec.SecretRefPolicy, options: options, validateBinding: spec.ValidateBinding,
	}, capabilities, nil
}

func compileOptionSpec(spec OptionSpec) (OptionSpec, error) {
	if err := validateOptionShape(spec); err != nil {
		return OptionSpec{}, err
	}
	compiled := spec
	compiled.DefaultValue = cloneString(spec.DefaultValue)
	compiled.MinInteger = cloneInt64(spec.MinInteger)
	compiled.MaxInteger = cloneInt64(spec.MaxInteger)
	compiled.AllowedValues = append([]string(nil), spec.AllowedValues...)
	if err := validateIntegerBounds(spec); err != nil {
		return OptionSpec{}, err
	}
	if spec.Kind == OptionEnum {
		if err := normalizeEnumValues(&compiled); err != nil {
			return OptionSpec{}, err
		}
	} else if len(spec.AllowedValues) != 0 {
		return OptionSpec{}, fmt.Errorf("%w: allowed values require an enum option", ErrInvalid)
	}
	if compiled.DefaultValue != nil {
		normalized, err := normalizeOptionValue(*compiled.DefaultValue, compiled)
		if err != nil {
			return OptionSpec{}, err
		}
		compiled.DefaultValue = &normalized
	}
	return compiled, nil
}

func validateOptionShape(spec OptionSpec) error {
	if spec.Kind != OptionString && spec.Kind != OptionBoolean && spec.Kind != OptionInteger && spec.Kind != OptionEnum {
		return fmt.Errorf("%w: unknown option kind", ErrInvalid)
	}
	if spec.Required && spec.DefaultValue != nil {
		return fmt.Errorf("%w: required option cannot have a default", ErrInvalid)
	}
	return nil
}

func validateIntegerBounds(spec OptionSpec) error {
	if spec.Kind != OptionInteger && (spec.MinInteger != nil || spec.MaxInteger != nil) {
		return fmt.Errorf("%w: integer bounds require an integer option", ErrInvalid)
	}
	if spec.MinInteger != nil && spec.MaxInteger != nil && *spec.MinInteger > *spec.MaxInteger {
		return fmt.Errorf("%w: option minimum exceeds maximum", ErrInvalid)
	}
	return nil
}

func normalizeEnumValues(compiled *OptionSpec) error {
	if len(compiled.AllowedValues) == 0 {
		return fmt.Errorf("%w: enum option requires allowed values", ErrInvalid)
	}
	seen := make(map[string]struct{}, len(compiled.AllowedValues))
	for i, value := range compiled.AllowedValues {
		value = strings.ToLower(strings.TrimSpace(value))
		if value == "" || len(value) > maxOptionValueLength || hasControl(value) {
			return fmt.Errorf("%w: enum value is invalid", ErrInvalid)
		}
		if _, exists := seen[value]; exists {
			return fmt.Errorf("%w: duplicate enum value", ErrInvalid)
		}
		seen[value] = struct{}{}
		compiled.AllowedValues[i] = value
	}
	return nil
}

func compileProviderName(raw string) (string, error) {
	provider := strings.ToLower(strings.TrimSpace(raw))
	if provider != raw || !validProviderName(provider) {
		return "", fmt.Errorf("%w: provider schema name must be normalized", ErrInvalid)
	}
	return provider, nil
}

func compileCapabilities(raw []Capability) ([]Capability, error) {
	if len(raw) == 0 {
		return nil, fmt.Errorf("%w: provider schema requires capabilities", ErrInvalid)
	}
	capabilities := make([]Capability, 0, len(raw))
	seen := make(map[Capability]struct{}, len(raw))
	for _, capability := range raw {
		if !validCapability(capability) {
			return nil, fmt.Errorf("%w: provider schema has unknown capability", ErrInvalid)
		}
		if _, exists := seen[capability]; exists {
			return nil, fmt.Errorf("%w: provider schema repeats capability %q", ErrInvalid, capability)
		}
		seen[capability] = struct{}{}
		capabilities = append(capabilities, capability)
	}
	return capabilities, nil
}

func compileEndpointSchema(endpointPolicy, secretRefPolicy FieldPolicy, raw []string) (map[string]struct{}, error) {
	if !validFieldPolicy(endpointPolicy) || !validFieldPolicy(secretRefPolicy) {
		return nil, fmt.Errorf("%w: provider schema has invalid field policy", ErrInvalid)
	}
	schemes := make(map[string]struct{}, len(raw))
	for _, scheme := range raw {
		normalized := strings.ToLower(strings.TrimSpace(scheme))
		if normalized != scheme || !validScheme(normalized) {
			return nil, fmt.Errorf("%w: endpoint scheme must be normalized", ErrInvalid)
		}
		if _, exists := schemes[normalized]; exists {
			return nil, fmt.Errorf("%w: duplicate endpoint scheme", ErrInvalid)
		}
		schemes[normalized] = struct{}{}
	}
	if endpointPolicy == FieldForbidden && len(schemes) != 0 {
		return nil, fmt.Errorf("%w: forbidden endpoint cannot declare schemes", ErrInvalid)
	}
	if endpointPolicy != FieldForbidden && len(schemes) == 0 {
		return nil, fmt.Errorf("%w: endpoint schema requires an allowed scheme", ErrInvalid)
	}
	return schemes, nil
}

func compileProviderOptions(raw map[string]OptionSpec) (map[string]OptionSpec, error) {
	options := make(map[string]OptionSpec, len(raw))
	for key, optionSpec := range raw {
		normalizedKey := strings.ToLower(strings.TrimSpace(key))
		if normalizedKey != key || !validOptionKey(normalizedKey) || sensitiveOptionKey(normalizedKey) {
			return nil, fmt.Errorf("%w: provider schema has invalid or sensitive option key", ErrInvalid)
		}
		compiledOption, err := compileOptionSpec(optionSpec)
		if err != nil {
			return nil, fmt.Errorf("%w: invalid schema for option %q", ErrInvalid, key)
		}
		options[key] = compiledOption
	}
	return options, nil
}

func (spec compiledProviderSpec) normalizeBinding(capability Capability, endpoint string, options map[string]string, secretRef string) (CapabilityBinding, error) {
	endpoint, err := normalizeEndpoint(endpoint, spec.endpointPolicy, spec.endpointSchemes)
	if err != nil {
		return CapabilityBinding{}, err
	}
	secretRef, err = normalizeSecretRef(secretRef, spec.secretRefPolicy)
	if err != nil {
		return CapabilityBinding{}, err
	}
	normalizedOptions := make(map[string]string, len(spec.options))
	for rawKey, rawValue := range options {
		key := strings.ToLower(strings.TrimSpace(rawKey))
		if key != rawKey || !validOptionKey(key) || sensitiveOptionKey(key) {
			return CapabilityBinding{}, fmt.Errorf("%w: invalid or sensitive option key", ErrInvalid)
		}
		optionSpec, exists := spec.options[key]
		if !exists {
			return CapabilityBinding{}, fmt.Errorf("%w: unknown option %q", ErrInvalid, key)
		}
		value, err := normalizeOptionValue(rawValue, optionSpec)
		if err != nil {
			return CapabilityBinding{}, fmt.Errorf("%w: invalid value for option %q", err, key)
		}
		normalizedOptions[key] = value
	}
	for key, optionSpec := range spec.options {
		if _, exists := normalizedOptions[key]; exists {
			continue
		}
		if optionSpec.DefaultValue != nil {
			normalizedOptions[key] = *optionSpec.DefaultValue
			continue
		}
		if optionSpec.Required {
			return CapabilityBinding{}, fmt.Errorf("%w: required option %q is missing", ErrInvalid, key)
		}
	}
	result := CapabilityBinding{
		Capability: capability, Provider: spec.provider, Endpoint: endpoint,
		Options: normalizedOptions, SecretRef: secretRef,
	}
	if spec.validateBinding != nil && !spec.validateBinding(result.Clone()) {
		return CapabilityBinding{}, fmt.Errorf("%w: provider binding is invalid", ErrInvalid)
	}
	return result, nil
}

func normalizeEndpoint(endpoint string, policy FieldPolicy, schemes map[string]struct{}) (string, error) {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		if policy == FieldRequired {
			return "", fmt.Errorf("%w: endpoint is required", ErrInvalid)
		}
		return "", nil
	}
	if policy == FieldForbidden {
		return "", fmt.Errorf("%w: endpoint is forbidden", ErrInvalid)
	}
	if len(endpoint) > maxEndpointLength || hasControl(endpoint) {
		return "", fmt.Errorf("%w: endpoint is invalid", ErrInvalid)
	}
	if strings.Contains(endpoint, "#") {
		return "", fmt.Errorf("%w: endpoint cannot contain a fragment", ErrInvalid)
	}
	parsed, err := url.Parse(endpoint)
	if err != nil || !validEndpointURL(parsed) {
		return "", fmt.Errorf("%w: endpoint must be an absolute network URI", ErrInvalid)
	}
	if endpointHasForbiddenParts(parsed) {
		return "", fmt.Errorf("%w: endpoint cannot contain credentials, query, or fragment", ErrInvalid)
	}
	if hasControl(parsed.Path) {
		return "", fmt.Errorf("%w: endpoint path is invalid", ErrInvalid)
	}
	parsed.Scheme = strings.ToLower(parsed.Scheme)
	if err := normalizeEndpointAuthority(parsed); err != nil {
		return "", err
	}
	if _, exists := schemes[parsed.Scheme]; !exists {
		return "", fmt.Errorf("%w: endpoint scheme is not allowed", ErrInvalid)
	}
	canonical := parsed.String()
	if len(canonical) > maxEndpointLength {
		return "", fmt.Errorf("%w: normalized endpoint is too long", ErrInvalid)
	}
	return canonical, nil
}

func validEndpointURL(parsed *url.URL) bool {
	return parsed != nil && parsed.Scheme != "" && parsed.Host != "" && parsed.Hostname() != "" && parsed.Opaque == "" && !strings.Contains(parsed.Host, ",")
}

func endpointHasForbiddenParts(parsed *url.URL) bool {
	return parsed.User != nil || parsed.RawQuery != "" || parsed.ForceQuery || parsed.Fragment != ""
}

func normalizeEndpointAuthority(parsed *url.URL) error {
	authority := parsed.Host
	hostname := parsed.Hostname()
	port := parsed.Port()
	if port != "" {
		portNumber, err := strconv.ParseUint(port, 10, 16)
		if err != nil || portNumber == 0 {
			return fmt.Errorf("%w: endpoint port is invalid", ErrInvalid)
		}
		port = strconv.FormatUint(portNumber, 10)
	}
	if strings.HasPrefix(authority, "[") {
		return normalizeIPv6Authority(parsed, authority, hostname, port)
	} else {
		return normalizeHostAuthority(parsed, authority, hostname, port)
	}
}

func normalizeIPv6Authority(parsed *url.URL, authority, hostname, port string) error {
	closingBracket := strings.LastIndex(authority, "]")
	if closingBracket < 0 {
		return fmt.Errorf("%w: endpoint host is invalid", ErrInvalid)
	}
	suffix := authority[closingBracket+1:]
	if suffix != "" && (!strings.HasPrefix(suffix, ":") || port == "") {
		return fmt.Errorf("%w: endpoint port is invalid", ErrInvalid)
	}
	address, zone := hostname, ""
	zoneIndex := strings.LastIndex(hostname, "%")
	if zoneIndex >= 0 {
		address, zone = hostname[:zoneIndex], hostname[zoneIndex+1:]
	}
	ip := net.ParseIP(address)
	if ip == nil || !strings.Contains(address, ":") || (zoneIndex >= 0 && !validZone(zone)) {
		return fmt.Errorf("%w: endpoint IPv6 host is invalid", ErrInvalid)
	}
	if mappedIPv4 := ip.To4(); mappedIPv4 != nil {
		if zoneIndex >= 0 {
			return fmt.Errorf("%w: IPv4-mapped endpoint cannot have a zone", ErrInvalid)
		}
		if port != "" {
			parsed.Host = net.JoinHostPort(mappedIPv4.String(), port)
		} else {
			parsed.Host = mappedIPv4.String()
		}
		return nil
	}
	canonicalHostname := ip.String()
	if zoneIndex >= 0 {
		canonicalHostname += "%" + zone
	}
	if port != "" {
		parsed.Host = net.JoinHostPort(canonicalHostname, port)
	} else {
		parsed.Host = "[" + canonicalHostname + "]"
	}
	return nil
}

func normalizeHostAuthority(parsed *url.URL, authority, hostname, port string) error {
	if strings.Count(authority, ":") > 1 || (strings.Contains(authority, ":") && port == "") {
		return fmt.Errorf("%w: endpoint host or port is invalid", ErrInvalid)
	}
	if net.ParseIP(hostname) == nil && !validDNSHostname(hostname) {
		return fmt.Errorf("%w: endpoint hostname is invalid", ErrInvalid)
	}
	hostname = strings.ToLower(hostname)
	if port != "" {
		parsed.Host = net.JoinHostPort(hostname, port)
	} else {
		parsed.Host = hostname
	}
	return nil
}

func validDNSHostname(hostname string) bool {
	if len(hostname) == 0 || len(hostname) > 253 {
		return false
	}
	hostname = strings.TrimSuffix(hostname, ".")
	if hostname == "" {
		return false
	}
	for _, label := range strings.Split(hostname, ".") {
		if len(label) == 0 || len(label) > 63 || !asciiLetterOrDigit(label[0]) || !asciiLetterOrDigit(label[len(label)-1]) {
			return false
		}
		for i := 1; i < len(label)-1; i++ {
			if !asciiLetterOrDigit(label[i]) && label[i] != '-' {
				return false
			}
		}
	}
	return true
}

func asciiLetterOrDigit(value byte) bool {
	return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9')
}

func validZone(zone string) bool {
	if zone == "" || len(zone) > 64 {
		return false
	}
	for _, value := range zone {
		if (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') ||
			(value >= '0' && value <= '9') || value == '_' || value == '-' || value == '.' {
			continue
		}
		return false
	}
	return true
}

func normalizeSecretRef(secretRef string, policy FieldPolicy) (string, error) {
	secretRef = strings.TrimSpace(secretRef)
	if secretRef == "" {
		if policy == FieldRequired {
			return "", fmt.Errorf("%w: secret reference is required", ErrInvalid)
		}
		return "", nil
	}
	if policy == FieldForbidden {
		return "", fmt.Errorf("%w: secret reference is forbidden", ErrInvalid)
	}
	if len(secretRef) > maxSecretRefLength || !validSecretRef(secretRef) {
		return "", fmt.Errorf("%w: secret reference is invalid", ErrInvalid)
	}
	return secretRef, nil
}

func normalizeOptionValue(value string, spec OptionSpec) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" || len(value) > maxOptionValueLength || hasControl(value) {
		return "", fmt.Errorf("%w: option value is invalid", ErrInvalid)
	}
	switch spec.Kind {
	case OptionString:
		return value, nil
	case OptionBoolean:
		parsed, err := strconv.ParseBool(strings.ToLower(value))
		if err != nil {
			return "", fmt.Errorf("%w: option must be boolean", ErrInvalid)
		}
		return strconv.FormatBool(parsed), nil
	case OptionInteger:
		parsed, err := strconv.ParseInt(value, 10, 64)
		if err != nil {
			return "", fmt.Errorf("%w: option must be an integer", ErrInvalid)
		}
		if spec.MinInteger != nil && parsed < *spec.MinInteger {
			return "", fmt.Errorf("%w: option is below its minimum", ErrInvalid)
		}
		if spec.MaxInteger != nil && parsed > *spec.MaxInteger {
			return "", fmt.Errorf("%w: option exceeds its maximum", ErrInvalid)
		}
		return strconv.FormatInt(parsed, 10), nil
	case OptionEnum:
		value = strings.ToLower(value)
		for _, allowed := range spec.AllowedValues {
			if value == allowed {
				return value, nil
			}
		}
		return "", fmt.Errorf("%w: option is outside its allowed values", ErrInvalid)
	default:
		return "", fmt.Errorf("%w: unknown option kind", ErrInvalid)
	}
}

func validFieldPolicy(policy FieldPolicy) bool {
	return policy == FieldForbidden || policy == FieldOptional || policy == FieldRequired
}

func validProviderName(provider string) bool {
	if len(provider) < 1 || len(provider) > 64 || provider[0] < 'a' || provider[0] > 'z' {
		return false
	}
	for i := 1; i < len(provider); i++ {
		c := provider[i]
		if (c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '_' && c != '-' {
			return false
		}
	}
	return true
}

func validOptionKey(key string) bool {
	if len(key) < 1 || len(key) > 64 || key[0] < 'a' || key[0] > 'z' {
		return false
	}
	for i := 1; i < len(key); i++ {
		c := key[i]
		if (c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '_' {
			return false
		}
	}
	return true
}

func sensitiveOptionKey(key string) bool {
	if _, exists := sensitiveOptionKeys[key]; exists {
		return true
	}
	for _, part := range strings.Split(key, "_") {
		switch part {
		case "password", "passwd", "pwd", "token", "secret", "credential", "credentials", "dsn":
			return true
		}
	}
	compact := strings.ReplaceAll(key, "_", "")
	for _, sequence := range sensitiveOptionSequences {
		if strings.Contains(compact, sequence) {
			return true
		}
	}
	return false
}

var sensitiveOptionKeys = map[string]struct{}{
	"api_key": {}, "access_key": {}, "secret_key": {}, "private_key": {},
	"connection_string": {},
}

var sensitiveOptionSequences = []string{
	"apikey", "accesskey", "secretkey", "privatekey", "connectionstring",
	"password", "passwd", "pwd", "passphrase", "token", "secret", "credential", "credentials", "dsn",
}

func validScheme(scheme string) bool {
	if scheme == "" || scheme[0] < 'a' || scheme[0] > 'z' {
		return false
	}
	for i := 1; i < len(scheme); i++ {
		c := scheme[i]
		if (c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '+' && c != '-' && c != '.' {
			return false
		}
	}
	return true
}

func validSecretRef(ref string) bool {
	for i, c := range ref {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			continue
		}
		if i > 0 && (c == '.' || c == '_' || c == ':' || c == '/' || c == '-') {
			continue
		}
		return false
	}
	return ref != ""
}

func hasControl(value string) bool {
	for _, r := range value {
		if unicode.IsControl(r) {
			return true
		}
	}
	return false
}

func contentDigest(schemaVersion int, bindings []CapabilityBinding) string {
	h := sha256.New()
	writeDigestString(h, strconv.Itoa(schemaVersion))
	writeDigestString(h, strconv.Itoa(len(bindings)))
	for _, binding := range bindings {
		writeDigestString(h, string(binding.Capability))
		writeDigestString(h, binding.Provider)
		writeDigestString(h, binding.Endpoint)
		keys := make([]string, 0, len(binding.Options))
		for key := range binding.Options {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		writeDigestString(h, strconv.Itoa(len(keys)))
		for _, key := range keys {
			writeDigestString(h, key)
			writeDigestString(h, binding.Options[key])
		}
		writeDigestString(h, binding.SecretRef)
	}
	return hex.EncodeToString(h.Sum(nil))
}

func writeDigestString(h hash.Hash, value string) {
	var length [8]byte
	binary.BigEndian.PutUint64(length[:], uint64(len(value)))
	_, _ = h.Write(length[:])
	_, _ = h.Write([]byte(value))
}

func bindingsEqual(left, right []CapabilityBinding) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i].Capability != right[i].Capability || left[i].Provider != right[i].Provider ||
			left[i].Endpoint != right[i].Endpoint || left[i].SecretRef != right[i].SecretRef ||
			!stringMapsEqual(left[i].Options, right[i].Options) {
			return false
		}
	}
	return true
}

func stringMapsEqual(left, right map[string]string) bool {
	if len(left) != len(right) {
		return false
	}
	for key, value := range left {
		rightValue, exists := right[key]
		if !exists || rightValue != value {
			return false
		}
	}
	return true
}

func cloneBindings(bindings []CapabilityBinding) []CapabilityBinding {
	if bindings == nil {
		return nil
	}
	clone := make([]CapabilityBinding, len(bindings))
	for i, binding := range bindings {
		clone[i] = binding.Clone()
	}
	return clone
}

func cloneStringMap(values map[string]string) map[string]string {
	if values == nil {
		return nil
	}
	clone := make(map[string]string, len(values))
	for key, value := range values {
		clone[key] = value
	}
	return clone
}

func cloneString(value *string) *string {
	if value == nil {
		return nil
	}
	clone := *value
	return &clone
}

func cloneInt64(value *int64) *int64 {
	if value == nil {
		return nil
	}
	clone := *value
	return &clone
}

func validateTenantID(id string) error {
	return validateCrockfordID(id, "t_", "tenant")
}

// ValidateTenantID validates the tenant scope used by runtime storage
// adapters. Tenant identity remains a backend-domain concern even when a
// runtime package uses it to key an in-process registry.
func ValidateTenantID(id string) error { return validateTenantID(id) }

func validateProfileID(id string) error {
	return validateCrockfordID(id, "bp_", "backend profile")
}

func validateCrockfordID(id, prefix, label string) error {
	if len(id) != len(prefix)+26 || !strings.HasPrefix(id, prefix) {
		return fmt.Errorf("%w: %s id must be %s followed by 26 Crockford characters", ErrInvalid, label, prefix)
	}
	payload := id[len(prefix):]
	if payload[0] > '7' {
		return fmt.Errorf("%w: %s id has invalid ULID padding bits", ErrInvalid, label)
	}
	for _, c := range payload {
		if !strings.ContainsRune(crockford, c) {
			return fmt.Errorf("%w: invalid %s id", ErrInvalid, label)
		}
	}
	return nil
}

const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

func newProfileID() (string, error) {
	var data [16]byte
	milliseconds := time.Now().UnixMilli()
	for i := 5; i >= 0; i-- {
		data[i] = byte(milliseconds)
		milliseconds >>= 8
	}
	if _, err := rand.Read(data[6:]); err != nil {
		return "", err
	}
	value := new(big.Int).SetBytes(data[:])
	var encoded [26]byte
	for i := len(encoded) - 1; i >= 0; i-- {
		encoded[i] = crockford[value.Uint64()&31]
		value.Rsh(value, 5)
	}
	return "bp_" + string(encoded[:]), nil
}
