"use client";

import { Plus, ShieldCheck } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ApiNotice, Button, Drawer, EmptyState, Field, PageHeader, StatCard, StatusBadge } from "../../../components/ui";
import { controlApi, ControlApiError, type Operator } from "../../../lib/control-api";

export default function OperatorsPage(){const[items,setItems]=useState<Operator[]>([]);const[error,setError]=useState<unknown>();const[drawer,setDrawer]=useState(false);const load=useCallback(()=>controlApi.listOperators().then((r)=>setItems(r.operators)).catch(setError),[]);useEffect(()=>{void load()},[load]);async function revoke(id:string){if(!confirm("确认撤销该平台管理员授权？"))return;try{await controlApi.revokeOperator(id);await load()}catch(caught){setError(caught instanceof ControlApiError&&caught.code==="LAST_OPERATOR"?new Error("不能撤销最后一名平台管理员"):caught)}}return <><PageHeader eyebrow="PLATFORM AUTHORIZATION" title="平台管理员" description="管理员授权独立于用户账号，并由服务端实时验证。" action={<Button onClick={()=>setDrawer(true)}><Plus size={15}/>授予管理员</Button>}/><ApiNotice error={error}/><div className="stats-grid"><StatCard detail="当前有效 Operator Grant" label="管理员" value={items.length}/><StatCard detail="用户、管理员和租户管理" label="能力" value="3"/><StatCard detail="系统始终保留至少一名管理员" label="保护规则" value="Last Operator"/></div><div className="panel">{items.length===0?<EmptyState detail="当前没有可展示的管理员授权。" title="没有管理员"/>:<div className="table-wrap"><table><thead><tr><th>管理员</th><th>用户 ID</th><th>授予者</th><th>授予时间</th><th>操作</th></tr></thead><tbody>{items.map((item)=><tr key={item.user_id}><td><div className="cell-primary"><span className="mini-avatar"><ShieldCheck size={14}/></span><span><strong>{item.display_name||item.username||item.user_id}</strong><br/><StatusBadge tone="blue">OPERATOR</StatusBadge></span></div></td><td>{item.user_id}</td><td>{item.granted_by||"SYSTEM_BOOTSTRAP"}</td><td>{new Date(item.granted_at).toLocaleString("zh-CN")}</td><td><Button onClick={()=>void revoke(item.user_id)} variant="danger">撤销</Button></td></tr>)}</tbody></table></div>}</div>{drawer&&<GrantDrawer onClose={()=>setDrawer(false)} onDone={()=>{setDrawer(false);void load()}}/>}</>}
function GrantDrawer({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const[id,setId]=useState("");const[error,setError]=useState<unknown>();async function submit(e:FormEvent){e.preventDefault();try{await controlApi.grantOperator(id);onDone()}catch(caught){setError(caught)}}return <Drawer description="输入已有平台用户的 ID。" onClose={onClose} title="授予平台管理员"><form className="form-stack" onSubmit={(e)=>void submit(e)}><ApiNotice error={error}/><Field label="用户 ID" onChange={(e)=>setId(e.target.value)} required value={id}/><div className="form-actions"><Button onClick={onClose} type="button" variant="secondary">取消</Button><Button type="submit">授予</Button></div></form></Drawer>}
