apiVersion: v1
kind: Namespace
metadata:
  name: trpc-agent
  labels:
    app.kubernetes.io/part-of: trpc-agent-service
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
