DROP TABLE IF EXISTS derived_jobs;
ALTER TABLE outbox_messages DROP CONSTRAINT IF EXISTS fk_outbox_event;
ALTER TABLE outbox_messages DROP CONSTRAINT IF EXISTS fk_outbox_inbox;
ALTER TABLE outbox_messages DROP COLUMN IF EXISTS fence;
ALTER TABLE outbox_messages DROP COLUMN IF EXISTS source_event_id;
ALTER TABLE outbox_messages DROP COLUMN IF EXISTS source_inbox_id;
ALTER TABLE outbox_messages DROP COLUMN IF EXISTS app_id;
ALTER TABLE inbox_messages DROP CONSTRAINT IF EXISTS fk_inbox_config_version;
DROP INDEX IF EXISTS uq_inbox_session_seq;
DROP INDEX IF EXISTS uq_inbox_tenant_id;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS completed_at;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS lease_until;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS claim_token;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS claim_owner;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS inbox_seq;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS config_version;
ALTER TABLE inbox_messages DROP COLUMN IF EXISTS inbox_id;
DROP INDEX IF EXISTS uq_message_events_tenant_inbox;
ALTER TABLE message_events DROP COLUMN IF EXISTS inbox_id;
