// Package model models tenant-scoped model provider configuration without
// resolving credentials or constructing runtime clients.
package model

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"math/big"
	"net"
	"net/url"
	"strconv"
	"strings"
	"time"
	"unicode"
)

const (
	// SchemaVersionV1 is the first supported Model Profile configuration schema.
	SchemaVersionV1 = 1
	maxEndpointLen  = 2048
	maxOptionLen    = 4096
	maxSecretRefLen = 256
)

// Status is the lifecycle state of a Model Profile.
type Status string

const (
	// StatusActive identifies a Profile that may admit new executions.
	StatusActive Status = "active"
	// StatusSuspended rejects new executions while remaining configurable.
	StatusSuspended Status = "suspended"
	// StatusDisabled is the terminal Profile lifecycle state.
	StatusDisabled Status = "disabled"
)

var (
	// ErrInvalid reports malformed Model Profile state or input.
	ErrInvalid = errors.New("invalid model profile")
	// ErrNotFound reports that a Profile does not exist in the requested scope.
	ErrNotFound = errors.New("model profile not found")
	// ErrConflict reports an optimistic-lock conflict.
	ErrConflict = errors.New("model profile version conflict")
	// ErrDuplicateKey reports a Profile key collision inside one tenant.
	ErrDuplicateKey = errors.New("model profile key already exists")
	// ErrDisabled reports an operation rejected by the terminal state.
	ErrDisabled = errors.New("model profile is disabled")
	// ErrInvalidTransition reports an unsupported lifecycle transition.
	ErrInvalidTransition = errors.New("invalid model profile status transition")
)

// GenerationConfig is the provider-neutral, controlled subset of generation
// parameters captured by a Model Profile.
type GenerationConfig struct {
	Temperature     *float64 `json:"temperature,omitempty"`
	TopP            *float64 `json:"top_p,omitempty"`
	MaxOutputTokens *int     `json:"max_output_tokens,omitempty"`
}

// Configuration is secret-free provider configuration accepted by a Profile.
// SecretRef is an opaque reference and never contains a resolved credential.
type Configuration struct {
	Provider   string            `json:"provider"`
	Model      string            `json:"model"`
	Endpoint   string            `json:"endpoint,omitempty"`
	Options    map[string]string `json:"options,omitempty"`
	SecretRef  string            `json:"secret_ref,omitempty"`
	Generation GenerationConfig  `json:"generation,omitempty"`
}

// Profile is the stable tenant-scoped Model Profile root.
type Profile struct {
	TenantID      string
	ProfileID     string
	ProfileKey    string
	DisplayName   string
	Description   string
	Status        Status
	SchemaVersion int
	Configuration Configuration
	ContentDigest string
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// CreateInput contains caller-selected fields for a new Profile. ProfileID
// is always generated by the service.
type CreateInput struct {
	TenantID      string
	ProfileKey    string
	DisplayName   string
	Description   string
	Status        Status
	SchemaVersion int
	Configuration Configuration
	Metadata      ChangeMetadata
}

// UpdateConfigurationInput replaces all mutable Profile configuration. The
// stable Profile key and lifecycle status remain unchanged.
type UpdateConfigurationInput struct {
	TenantID        string
	ProfileID       string
	ExpectedVersion int64
	DisplayName     string
	Description     string
	SchemaVersion   int
	Configuration   Configuration
	Metadata        ChangeMetadata
}

// TransitionStatusInput requests an optimistic-lock protected lifecycle
// transition.
type TransitionStatusInput struct {
	TenantID        string
	ProfileID       string
	ExpectedVersion int64
	NextStatus      Status
	Metadata        ChangeMetadata
}

// NewProfile validates, normalizes, and constructs a Model Profile.
func NewProfile(input CreateInput, catalog *ProviderCatalog) (*Profile, error) {
	if err := validateTenantID(input.TenantID); err != nil {
		return nil, err
	}
	key, err := normalizeProfileKey(input.ProfileKey)
	if err != nil {
		return nil, err
	}
	displayName, description, err := normalizeMetadata(input.DisplayName, input.Description)
	if err != nil {
		return nil, err
	}
	status := input.Status
	if status == "" {
		status = StatusActive
	}
	if status != StatusActive && status != StatusSuspended {
		if status == StatusDisabled {
			return nil, fmt.Errorf("%w: new profile cannot be disabled", ErrInvalid)
		}
		return nil, fmt.Errorf("%w: unknown status", ErrInvalid)
	}
	schemaVersion := input.SchemaVersion
	if schemaVersion == 0 {
		schemaVersion = SchemaVersionV1
	}
	configuration, digest, err := normalizeConfiguration(schemaVersion, input.Configuration, catalog)
	if err != nil {
		return nil, err
	}
	id, err := newProfileID()
	if err != nil {
		return nil, fmt.Errorf("generate model profile id: %w", err)
	}
	now := time.Now().UTC()
	return &Profile{
		TenantID: input.TenantID, ProfileID: id, ProfileKey: key,
		DisplayName: displayName, Description: description, Status: status,
		SchemaVersion: schemaVersion, Configuration: configuration,
		ContentDigest: digest, Version: 1, CreatedAt: now, UpdatedAt: now,
	}, nil
}

// Clone returns a defensive copy suitable for repository and snapshot
// boundaries.
func (p Profile) Clone() Profile {
	clone := p
	clone.Configuration = p.Configuration.Clone()
	return clone
}

// Clone returns a defensive copy of the configuration and its nested fields.
func (c Configuration) Clone() Configuration {
	clone := c
	clone.Options = cloneStringMap(c.Options)
	clone.Generation = c.Generation.Clone()
	return clone
}

// Clone returns a defensive copy of the generation parameters.
func (c GenerationConfig) Clone() GenerationConfig {
	clone := c
	if c.Temperature != nil {
		value := *c.Temperature
		clone.Temperature = &value
	}
	if c.TopP != nil {
		value := *c.TopP
		clone.TopP = &value
	}
	if c.MaxOutputTokens != nil {
		value := *c.MaxOutputTokens
		clone.MaxOutputTokens = &value
	}
	return clone
}

// Validate checks the complete Profile invariants against the trusted
// ProviderCatalog that accepted the configuration.
func (p Profile) Validate(catalog *ProviderCatalog) error {
	if err := validateTenantID(p.TenantID); err != nil {
		return err
	}
	if err := validateProfileID(p.ProfileID); err != nil {
		return err
	}
	key, err := normalizeProfileKey(p.ProfileKey)
	if err != nil {
		return err
	}
	if key != p.ProfileKey {
		return fmt.Errorf("%w: profile key must be normalized", ErrInvalid)
	}
	displayName, description, err := normalizeMetadata(p.DisplayName, p.Description)
	if err != nil {
		return err
	}
	if displayName != p.DisplayName || description != p.Description {
		return fmt.Errorf("%w: profile metadata must be normalized", ErrInvalid)
	}
	if !validStatus(p.Status) {
		return fmt.Errorf("%w: unknown status", ErrInvalid)
	}
	configuration, digest, err := normalizeConfiguration(p.SchemaVersion, p.Configuration, catalog)
	if err != nil {
		return err
	}
	if !configurationEqual(configuration, p.Configuration) {
		return fmt.Errorf("%w: configuration must be normalized", ErrInvalid)
	}
	if p.ContentDigest != digest {
		return fmt.Errorf("%w: content digest does not match configuration", ErrInvalid)
	}
	if p.Version < 1 || p.CreatedAt.IsZero() || p.UpdatedAt.IsZero() || p.UpdatedAt.Before(p.CreatedAt) ||
		p.CreatedAt.Location() != time.UTC || p.UpdatedAt.Location() != time.UTC {
		return fmt.Errorf("%w: version and timestamps must be initialized, UTC, and ordered", ErrInvalid)
	}
	return nil
}

// CanAcceptExecution reports whether the Profile may be selected for a new
// execution.
func (p Profile) CanAcceptExecution() bool { return p.Status == StatusActive }

// CanTransitionTo reports whether a lifecycle transition is allowed.
func (p Profile) CanTransitionTo(next Status) bool {
	switch p.Status {
	case StatusActive:
		return next == StatusSuspended || next == StatusDisabled
	case StatusSuspended:
		return next == StatusActive || next == StatusDisabled
	default:
		return false
	}
}

// FieldPolicy controls whether a provider field is accepted.
type FieldPolicy string

const (
	// FieldForbidden rejects a field when it is present.
	FieldForbidden FieldPolicy = "forbidden"
	// FieldOptional accepts an omitted or valid field.
	FieldOptional FieldPolicy = "optional"
	// FieldRequired requires a valid field.
	FieldRequired FieldPolicy = "required"
)

// OptionKind controls normalization of an allowlisted provider option.
type OptionKind string

const (
	// OptionString is a bounded, non-control string.
	OptionString OptionKind = "string"
	// OptionBoolean is normalized to true or false.
	OptionBoolean OptionKind = "boolean"
	// OptionInteger is a bounded base-10 integer.
	OptionInteger OptionKind = "integer"
	// OptionEnum is a value from AllowedValues.
	OptionEnum OptionKind = "enum"
)

// OptionSpec declares the accepted shape of one provider option.
type OptionSpec struct {
	Kind          OptionKind
	Required      bool
	DefaultValue  *string
	AllowedValues []string
	MinInteger    *int64
	MaxInteger    *int64
}

// ProviderSpec declares one trusted provider and its accepted model and
// configuration schema.
type ProviderSpec struct {
	Provider        string
	Models          []string
	EndpointPolicy  FieldPolicy
	EndpointSchemes []string
	// EndpointHosts contains the exact normalized hostnames or IP addresses
	// accepted for an endpoint. IPv6 entries are written without brackets.
	EndpointHosts   []string
	SecretRefPolicy FieldPolicy
	Options         map[string]OptionSpec
}

type compiledProviderSpec struct {
	provider        string
	models          map[string]struct{}
	endpointPolicy  FieldPolicy
	endpointSchemes map[string]struct{}
	endpointHosts   map[string]struct{}
	secretRefPolicy FieldPolicy
	options         map[string]OptionSpec
}

// ProviderCatalog is an immutable trusted registry used to reject unknown
// provider/model/options before they enter a runtime snapshot.
type ProviderCatalog struct {
	providers map[string]compiledProviderSpec
}

// NewProviderCatalog validates and defensively copies provider schemas.
func NewProviderCatalog(specs ...ProviderSpec) (*ProviderCatalog, error) {
	if len(specs) == 0 {
		return nil, fmt.Errorf("%w: provider catalog cannot be empty", ErrInvalid)
	}
	catalog := &ProviderCatalog{providers: make(map[string]compiledProviderSpec, len(specs))}
	for _, spec := range specs {
		compiled, err := compileProviderSpec(spec)
		if err != nil {
			return nil, err
		}
		if _, exists := catalog.providers[compiled.provider]; exists {
			return nil, fmt.Errorf("%w: duplicate provider schema", ErrInvalid)
		}
		catalog.providers[compiled.provider] = compiled
	}
	return catalog, nil
}

// NormalizeConfiguration validates and returns a canonical defensive copy.
func (c *ProviderCatalog) NormalizeConfiguration(configuration Configuration) (Configuration, error) {
	if c == nil || len(c.providers) == 0 {
		return Configuration{}, fmt.Errorf("%w: provider catalog is required", ErrInvalid)
	}
	provider := strings.ToLower(strings.TrimSpace(configuration.Provider))
	spec, exists := c.providers[provider]
	if !exists {
		return Configuration{}, fmt.Errorf("%w: provider is not registered", ErrInvalid)
	}
	modelName := strings.ToLower(strings.TrimSpace(configuration.Model))
	if _, exists := spec.models[modelName]; !exists {
		return Configuration{}, fmt.Errorf("%w: model is not registered for provider", ErrInvalid)
	}
	endpoint, err := normalizeEndpoint(configuration.Endpoint, spec.endpointPolicy, spec.endpointSchemes, spec.endpointHosts)
	if err != nil {
		return Configuration{}, err
	}
	secretRef, err := normalizeSecretRef(configuration.SecretRef, spec.secretRefPolicy)
	if err != nil {
		return Configuration{}, err
	}
	options, err := normalizeOptions(configuration.Options, spec.options)
	if err != nil {
		return Configuration{}, err
	}
	generation, err := normalizeGeneration(configuration.Generation)
	if err != nil {
		return Configuration{}, err
	}
	return Configuration{
		Provider: provider, Model: modelName, Endpoint: endpoint,
		Options: options, SecretRef: secretRef, Generation: generation,
	}, nil
}

func compileProviderSpec(spec ProviderSpec) (compiledProviderSpec, error) {
	provider := strings.ToLower(strings.TrimSpace(spec.Provider))
	if provider == "" || provider != spec.Provider || !validName(provider) {
		return compiledProviderSpec{}, fmt.Errorf("%w: provider schema name must be normalized", ErrInvalid)
	}
	models, err := compileProviderModels(spec.Models)
	if err != nil {
		return compiledProviderSpec{}, err
	}
	schemes, hosts, err := compileEndpointRules(spec)
	if err != nil {
		return compiledProviderSpec{}, err
	}
	options, err := compileProviderOptions(spec.Options)
	if err != nil {
		return compiledProviderSpec{}, err
	}
	return compiledProviderSpec{
		provider: provider, models: models, endpointPolicy: spec.EndpointPolicy,
		endpointSchemes: schemes, endpointHosts: hosts, secretRefPolicy: spec.SecretRefPolicy, options: options,
	}, nil
}

func compileProviderModels(values []string) (map[string]struct{}, error) {
	if len(values) == 0 {
		return nil, fmt.Errorf("%w: provider schema requires models", ErrInvalid)
	}
	models := make(map[string]struct{}, len(values))
	for _, value := range values {
		normalized := strings.ToLower(strings.TrimSpace(value))
		if normalized == "" || normalized != value || !validName(normalized) {
			return nil, fmt.Errorf("%w: provider schema has invalid model", ErrInvalid)
		}
		if _, exists := models[normalized]; exists {
			return nil, fmt.Errorf("%w: provider schema repeats model", ErrInvalid)
		}
		models[normalized] = struct{}{}
	}
	return models, nil
}

func compileEndpointRules(spec ProviderSpec) (map[string]struct{}, map[string]struct{}, error) {
	if !validFieldPolicy(spec.EndpointPolicy) || !validFieldPolicy(spec.SecretRefPolicy) {
		return nil, nil, fmt.Errorf("%w: provider schema has invalid field policy", ErrInvalid)
	}
	schemes := make(map[string]struct{}, len(spec.EndpointSchemes))
	for _, scheme := range spec.EndpointSchemes {
		normalized := strings.ToLower(strings.TrimSpace(scheme))
		if normalized != scheme || !validName(normalized) {
			return nil, nil, fmt.Errorf("%w: endpoint scheme is invalid", ErrInvalid)
		}
		if _, exists := schemes[normalized]; exists {
			return nil, nil, fmt.Errorf("%w: duplicate endpoint scheme", ErrInvalid)
		}
		schemes[normalized] = struct{}{}
	}
	if spec.EndpointPolicy == FieldForbidden && len(schemes) != 0 {
		return nil, nil, fmt.Errorf("%w: forbidden endpoint cannot declare schemes", ErrInvalid)
	}
	if spec.EndpointPolicy != FieldForbidden && len(schemes) == 0 {
		return nil, nil, fmt.Errorf("%w: endpoint schema requires an allowed scheme", ErrInvalid)
	}
	hosts := make(map[string]struct{}, len(spec.EndpointHosts))
	for _, host := range spec.EndpointHosts {
		normalized, err := normalizeEndpointHost(host)
		if err != nil || normalized != host {
			return nil, nil, fmt.Errorf("%w: endpoint host is invalid", ErrInvalid)
		}
		if _, exists := hosts[normalized]; exists {
			return nil, nil, fmt.Errorf("%w: duplicate endpoint host", ErrInvalid)
		}
		hosts[normalized] = struct{}{}
	}
	if spec.EndpointPolicy == FieldForbidden && len(hosts) != 0 {
		return nil, nil, fmt.Errorf("%w: forbidden endpoint cannot declare hosts", ErrInvalid)
	}
	if spec.EndpointPolicy != FieldForbidden && len(hosts) == 0 {
		return nil, nil, fmt.Errorf("%w: endpoint schema requires an allowed host", ErrInvalid)
	}
	return schemes, hosts, nil
}

func compileProviderOptions(specs map[string]OptionSpec) (map[string]OptionSpec, error) {
	options := make(map[string]OptionSpec, len(specs))
	for key, option := range specs {
		normalizedKey := strings.ToLower(strings.TrimSpace(key))
		if normalizedKey != key || !validOptionKey(normalizedKey) || sensitiveOptionKey(normalizedKey) {
			return nil, fmt.Errorf("%w: provider schema has invalid option key", ErrInvalid)
		}
		compiled, err := compileOptionSpec(option)
		if err != nil {
			return nil, fmt.Errorf("%w: invalid schema for option", ErrInvalid)
		}
		options[normalizedKey] = compiled
	}
	return options, nil
}

func compileOptionSpec(spec OptionSpec) (OptionSpec, error) {
	if spec.Kind != OptionString && spec.Kind != OptionBoolean && spec.Kind != OptionInteger && spec.Kind != OptionEnum {
		return OptionSpec{}, fmt.Errorf("%w: unknown option kind", ErrInvalid)
	}
	if spec.Required && spec.DefaultValue != nil {
		return OptionSpec{}, fmt.Errorf("%w: required option cannot have a default", ErrInvalid)
	}
	compiled := spec
	compiled.DefaultValue = cloneString(spec.DefaultValue)
	compiled.AllowedValues = append([]string(nil), spec.AllowedValues...)
	compiled.MinInteger = cloneInt64(spec.MinInteger)
	compiled.MaxInteger = cloneInt64(spec.MaxInteger)
	if err := validateOptionBounds(spec); err != nil {
		return OptionSpec{}, err
	}
	if spec.Kind == OptionEnum {
		values, err := compileEnumValues(spec.AllowedValues)
		if err != nil {
			return OptionSpec{}, err
		}
		compiled.AllowedValues = values
	} else if len(spec.AllowedValues) != 0 {
		return OptionSpec{}, fmt.Errorf("%w: allowed values require enum option", ErrInvalid)
	}
	if err := normalizeOptionDefault(&compiled); err != nil {
		return OptionSpec{}, err
	}
	return compiled, nil
}

func validateOptionBounds(spec OptionSpec) error {
	if spec.Kind != OptionInteger && (spec.MinInteger != nil || spec.MaxInteger != nil) {
		return fmt.Errorf("%w: integer bounds require integer option", ErrInvalid)
	}
	if spec.MinInteger != nil && spec.MaxInteger != nil && *spec.MinInteger > *spec.MaxInteger {
		return fmt.Errorf("%w: option minimum exceeds maximum", ErrInvalid)
	}
	return nil
}

func compileEnumValues(values []string) ([]string, error) {
	if len(values) == 0 {
		return nil, fmt.Errorf("%w: enum option requires allowed values", ErrInvalid)
	}
	normalizedValues := append([]string(nil), values...)
	seen := make(map[string]struct{}, len(values))
	for index, value := range values {
		normalized := strings.ToLower(strings.TrimSpace(value))
		if normalized == "" || len([]rune(normalized)) > maxOptionLen || hasControl(normalized) {
			return nil, fmt.Errorf("%w: enum value is invalid", ErrInvalid)
		}
		if _, exists := seen[normalized]; exists {
			return nil, fmt.Errorf("%w: duplicate enum value", ErrInvalid)
		}
		seen[normalized] = struct{}{}
		normalizedValues[index] = normalized
	}
	return normalizedValues, nil
}

func normalizeOptionDefault(compiled *OptionSpec) error {
	if compiled.DefaultValue == nil {
		return nil
	}
	normalized, err := normalizeOptionValue(*compiled.DefaultValue, *compiled)
	if err != nil {
		return err
	}
	compiled.DefaultValue = &normalized
	return nil
}

func normalizeEndpoint(endpoint string, policy FieldPolicy, schemes, hosts map[string]struct{}) (string, error) {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		if policy == FieldRequired {
			return "", fmt.Errorf("%w: endpoint is required", ErrInvalid)
		}
		return "", nil
	}
	if policy == FieldForbidden {
		return "", fmt.Errorf("%w: endpoint is not allowed", ErrInvalid)
	}
	parsed, err := parseEndpoint(endpoint, schemes)
	if err != nil {
		return "", err
	}
	if err := normalizeEndpointAuthority(parsed); err != nil {
		return "", err
	}
	host, err := normalizeEndpointHost(parsed.Hostname())
	if err != nil {
		return "", err
	}
	if _, exists := hosts[host]; !exists {
		return "", fmt.Errorf("%w: endpoint host is not allowed", ErrInvalid)
	}
	canonical := parsed.String()
	if len(canonical) > maxEndpointLen {
		return "", fmt.Errorf("%w: normalized endpoint is too long", ErrInvalid)
	}
	return canonical, nil
}

func parseEndpoint(endpoint string, schemes map[string]struct{}) (*url.URL, error) {
	if len(endpoint) > maxEndpointLen || hasControl(endpoint) {
		return nil, fmt.Errorf("%w: endpoint is invalid", ErrInvalid)
	}
	parsed, err := url.Parse(endpoint)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" || parsed.Hostname() == "" || parsed.Opaque != "" || strings.Contains(parsed.Host, ",") || parsed.User != nil || parsed.RawQuery != "" || parsed.ForceQuery || parsed.Fragment != "" {
		return nil, fmt.Errorf("%w: endpoint is invalid", ErrInvalid)
	}
	if hasControl(parsed.Path) {
		return nil, fmt.Errorf("%w: endpoint path is invalid", ErrInvalid)
	}
	parsed.Scheme = strings.ToLower(parsed.Scheme)
	if _, exists := schemes[parsed.Scheme]; !exists {
		return nil, fmt.Errorf("%w: endpoint scheme is not allowed", ErrInvalid)
	}
	return parsed, nil
}

func normalizeEndpointHost(hostname string) (string, error) {
	if ip := net.ParseIP(hostname); ip != nil {
		return ip.String(), nil
	}
	if !validDNSHostname(hostname) {
		return "", fmt.Errorf("%w: endpoint hostname is invalid", ErrInvalid)
	}
	return strings.ToLower(strings.TrimSuffix(hostname, ".")), nil
}

func normalizeEndpointAuthority(parsed *url.URL) error {
	hostname := parsed.Hostname()
	port := parsed.Port()
	if strings.Contains(parsed.Host, ":") && port == "" && !strings.Contains(hostname, ":") {
		return fmt.Errorf("%w: endpoint port is invalid", ErrInvalid)
	}
	if port != "" {
		parsedPort, err := strconv.ParseUint(port, 10, 16)
		if err != nil || parsedPort == 0 {
			return fmt.Errorf("%w: endpoint port is invalid", ErrInvalid)
		}
		port = strconv.FormatUint(parsedPort, 10)
	}
	if ip := net.ParseIP(hostname); ip != nil {
		if strings.Contains(hostname, ":") {
			if port == "" {
				parsed.Host = "[" + ip.String() + "]"
			} else {
				parsed.Host = net.JoinHostPort(ip.String(), port)
			}
		} else if port == "" {
			parsed.Host = ip.String()
		} else {
			parsed.Host = net.JoinHostPort(ip.String(), port)
		}
		return nil
	}
	if !validDNSHostname(hostname) {
		return fmt.Errorf("%w: endpoint hostname is invalid", ErrInvalid)
	}
	hostname = strings.ToLower(strings.TrimSuffix(hostname, "."))
	if port == "" {
		parsed.Host = hostname
	} else {
		parsed.Host = net.JoinHostPort(hostname, port)
	}
	return nil
}

func validDNSHostname(hostname string) bool {
	if len(hostname) == 0 || len(hostname) > 253 {
		return false
	}
	hostname = strings.TrimSuffix(hostname, ".")
	if hostname == "" {
		return false
	}
	for _, label := range strings.Split(hostname, ".") {
		if len(label) == 0 || len(label) > 63 || !asciiLetterOrDigit(label[0]) || !asciiLetterOrDigit(label[len(label)-1]) {
			return false
		}
		for index := 1; index < len(label)-1; index++ {
			if !asciiLetterOrDigit(label[index]) && label[index] != '-' {
				return false
			}
		}
	}
	return true
}

func asciiLetterOrDigit(value byte) bool {
	return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9')
}

func normalizeSecretRef(secretRef string, policy FieldPolicy) (string, error) {
	secretRef = strings.TrimSpace(secretRef)
	if secretRef == "" {
		if policy == FieldRequired {
			return "", fmt.Errorf("%w: secret reference is required", ErrInvalid)
		}
		return "", nil
	}
	if policy == FieldForbidden || len([]rune(secretRef)) > maxSecretRefLen || hasControl(secretRef) || hasSpace(secretRef) {
		return "", fmt.Errorf("%w: secret reference is invalid", ErrInvalid)
	}
	return secretRef, nil
}

func normalizeOptions(options map[string]string, specs map[string]OptionSpec) (map[string]string, error) {
	normalized := make(map[string]string, len(specs))
	for rawKey, rawValue := range options {
		key := strings.ToLower(strings.TrimSpace(rawKey))
		if key == "" || !validOptionKey(key) || sensitiveOptionKey(key) || key != rawKey {
			return nil, fmt.Errorf("%w: option key is invalid", ErrInvalid)
		}
		if _, exists := normalized[key]; exists {
			return nil, fmt.Errorf("%w: duplicate option key", ErrInvalid)
		}
		spec, exists := specs[key]
		if !exists {
			return nil, fmt.Errorf("%w: option is not registered", ErrInvalid)
		}
		value, err := normalizeOptionValue(rawValue, spec)
		if err != nil {
			return nil, err
		}
		normalized[key] = value
	}
	for key, spec := range specs {
		if _, exists := normalized[key]; exists {
			continue
		}
		if spec.DefaultValue != nil {
			normalized[key] = *spec.DefaultValue
			continue
		}
		if spec.Required {
			return nil, fmt.Errorf("%w: required option is missing", ErrInvalid)
		}
	}
	return normalized, nil
}

func normalizeOptionValue(value string, spec OptionSpec) (string, error) {
	value = strings.TrimSpace(value)
	if len([]rune(value)) > maxOptionLen || hasControl(value) {
		return "", fmt.Errorf("%w: option value is invalid", ErrInvalid)
	}
	switch spec.Kind {
	case OptionString:
		return value, nil
	case OptionBoolean:
		parsed, err := strconv.ParseBool(value)
		if err != nil {
			return "", fmt.Errorf("%w: option value is invalid", ErrInvalid)
		}
		return strconv.FormatBool(parsed), nil
	case OptionInteger:
		parsed, err := strconv.ParseInt(value, 10, 64)
		if err != nil || (spec.MinInteger != nil && parsed < *spec.MinInteger) || (spec.MaxInteger != nil && parsed > *spec.MaxInteger) {
			return "", fmt.Errorf("%w: option value is invalid", ErrInvalid)
		}
		return strconv.FormatInt(parsed, 10), nil
	case OptionEnum:
		value = strings.ToLower(value)
		for _, allowed := range spec.AllowedValues {
			if value == allowed {
				return value, nil
			}
		}
		return "", fmt.Errorf("%w: option value is invalid", ErrInvalid)
	default:
		return "", fmt.Errorf("%w: option schema is invalid", ErrInvalid)
	}
}

func normalizeGeneration(generation GenerationConfig) (GenerationConfig, error) {
	normalized := generation.Clone()
	if normalized.Temperature != nil && (math.IsNaN(*normalized.Temperature) || math.IsInf(*normalized.Temperature, 0) || *normalized.Temperature < 0 || *normalized.Temperature > 2) {
		return GenerationConfig{}, fmt.Errorf("%w: temperature is invalid", ErrInvalid)
	}
	if normalized.TopP != nil && (math.IsNaN(*normalized.TopP) || math.IsInf(*normalized.TopP, 0) || *normalized.TopP < 0 || *normalized.TopP > 1) {
		return GenerationConfig{}, fmt.Errorf("%w: top_p is invalid", ErrInvalid)
	}
	if normalized.MaxOutputTokens != nil && (*normalized.MaxOutputTokens <= 0 || *normalized.MaxOutputTokens > 1_000_000) {
		return GenerationConfig{}, fmt.Errorf("%w: max output tokens is invalid", ErrInvalid)
	}
	return normalized, nil
}

func normalizeConfiguration(schemaVersion int, configuration Configuration, catalog *ProviderCatalog) (Configuration, string, error) {
	if schemaVersion != SchemaVersionV1 {
		return Configuration{}, "", fmt.Errorf("%w: unsupported schema version", ErrInvalid)
	}
	normalized, err := catalog.NormalizeConfiguration(configuration)
	if err != nil {
		return Configuration{}, "", err
	}
	return normalized, contentDigest(schemaVersion, normalized), nil
}

func contentDigest(schemaVersion int, configuration Configuration) string {
	payload := struct {
		SchemaVersion int           `json:"schema_version"`
		Configuration Configuration `json:"configuration"`
	}{schemaVersion, configuration}
	encoded, _ := json.Marshal(payload)
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:])
}

func configurationEqual(left, right Configuration) bool {
	if left.Provider != right.Provider || left.Model != right.Model || left.Endpoint != right.Endpoint || left.SecretRef != right.SecretRef || !generationEqual(left.Generation, right.Generation) || len(left.Options) != len(right.Options) {
		return false
	}
	for key, value := range left.Options {
		if right.Options[key] != value {
			return false
		}
	}
	return true
}

func generationEqual(left, right GenerationConfig) bool {
	return sameFloat64(left.Temperature, right.Temperature) && sameFloat64(left.TopP, right.TopP) && sameInt(left.MaxOutputTokens, right.MaxOutputTokens)
}

func sameFloat64(left, right *float64) bool {
	if left == nil || right == nil {
		return left == nil && right == nil
	}
	return *left == *right
}

func sameInt(left, right *int) bool {
	if left == nil || right == nil {
		return left == nil && right == nil
	}
	return *left == *right
}

func normalizeMetadata(displayName, description string) (string, string, error) {
	displayName = strings.TrimSpace(displayName)
	description = strings.TrimSpace(description)
	if n := len([]rune(displayName)); n < 1 || n > 200 {
		return "", "", fmt.Errorf("%w: display name must contain 1-200 characters", ErrInvalid)
	}
	if len([]rune(description)) > 2000 {
		return "", "", fmt.Errorf("%w: description is too long", ErrInvalid)
	}
	return displayName, description, nil
}

func normalizeProfileKey(key string) (string, error) {
	key = strings.ToLower(strings.TrimSpace(key))
	if len(key) < 2 || len(key) > 64 || key[0] < 'a' || key[0] > 'z' {
		return "", fmt.Errorf("%w: profile key is invalid", ErrInvalid)
	}
	for index := 1; index < len(key); index++ {
		value := key[index]
		if (value < 'a' || value > 'z') && (value < '0' || value > '9') && value != '-' {
			return "", fmt.Errorf("%w: profile key is invalid", ErrInvalid)
		}
	}
	return key, nil
}

func validateTenantID(id string) error { return validateCrockfordID(id, "t_", "tenant") }

// ValidateTenantID validates the tenant scope used by runtime adapters.
// Tenant identity remains a model-domain concern even when a runtime package
// uses it to key an in-process registry.
func ValidateTenantID(id string) error { return validateTenantID(id) }

func validateProfileID(id string) error { return validateCrockfordID(id, "mp_", "model profile") }

func validateCrockfordID(id, prefix, label string) error {
	payload := strings.TrimPrefix(id, prefix)
	if payload == id || len(payload) != 26 {
		return fmt.Errorf("%w: %s id is invalid", ErrInvalid, label)
	}
	if payload[0] > '7' {
		return fmt.Errorf("%w: %s id has invalid padding", ErrInvalid, label)
	}
	for _, value := range payload {
		if !strings.ContainsRune("0123456789ABCDEFGHJKMNPQRSTVWXYZ", value) {
			return fmt.Errorf("%w: %s id is invalid", ErrInvalid, label)
		}
	}
	return nil
}

func validStatus(status Status) bool {
	return status == StatusActive || status == StatusSuspended || status == StatusDisabled
}

func validFieldPolicy(policy FieldPolicy) bool {
	return policy == FieldForbidden || policy == FieldOptional || policy == FieldRequired
}

func validName(value string) bool {
	if value == "" {
		return false
	}
	for _, character := range value {
		if (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '-' && character != '_' && character != '.' {
			return false
		}
	}
	return true
}

func validOptionKey(value string) bool {
	if value == "" {
		return false
	}
	for _, character := range value {
		if (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '_' && character != '-' {
			return false
		}
	}
	return true
}

func sensitiveOptionKey(value string) bool {
	if _, exists := sensitiveOptionKeys[value]; exists {
		return true
	}
	separatorNormalized := strings.NewReplacer("-", "_").Replace(value)
	for _, part := range strings.Split(separatorNormalized, "_") {
		switch part {
		case "password", "passwd", "pwd", "token", "secret", "credential", "credentials", "dsn":
			return true
		}
	}
	compact := strings.NewReplacer("_", "", "-", "").Replace(value)
	for _, sequence := range sensitiveOptionSequences {
		if strings.Contains(compact, sequence) {
			return true
		}
	}
	return false
}

var sensitiveOptionKeys = map[string]struct{}{
	"api_key": {}, "access_key": {}, "secret_key": {}, "private_key": {},
	"connection_string": {},
}

var sensitiveOptionSequences = []string{
	"apikey", "accesskey", "secretkey", "privatekey", "connectionstring",
	"password", "passwd", "pwd", "passphrase", "token", "secret", "credential", "credentials", "dsn",
}

func hasControl(value string) bool {
	for _, character := range value {
		if unicode.IsControl(character) {
			return true
		}
	}
	return false
}

func hasSpace(value string) bool {
	for _, character := range value {
		if unicode.IsSpace(character) {
			return true
		}
	}
	return false
}

func cloneStringMap(source map[string]string) map[string]string {
	if source == nil {
		return nil
	}
	clone := make(map[string]string, len(source))
	for key, value := range source {
		clone[key] = value
	}
	return clone
}

func cloneString(value *string) *string {
	if value == nil {
		return nil
	}
	clone := *value
	return &clone
}

func cloneInt64(value *int64) *int64 {
	if value == nil {
		return nil
	}
	clone := *value
	return &clone
}

func newProfileID() (string, error) {
	var data [16]byte
	milliseconds := time.Now().UnixMilli()
	for index := 5; index >= 0; index-- {
		data[index] = byte(milliseconds)
		milliseconds >>= 8
	}
	if _, err := rand.Read(data[6:]); err != nil {
		return "", err
	}
	value := new(big.Int).SetBytes(data[:])
	const alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
	var encoded [26]byte
	for index := len(encoded) - 1; index >= 0; index-- {
		encoded[index] = alphabet[value.Uint64()&31]
		value.Rsh(value, 5)
	}
	return "mp_" + string(encoded[:]), nil
}
