package webui

const webUIHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>tRPC Agent WebUI IM</title><link rel="stylesheet" href="/webui/style.css"></head>
<body><main><header><div><span class="eyebrow">LOCAL CHANNEL ADAPTER</span><h1>WebUI IM</h1></div><div id="status" class="status">未连接</div></header>
<section class="settings"><label>Route Key<input id="route" autocomplete="off"></label><label>Account ID<input id="account" autocomplete="off"></label>
<label>User ID<input id="user" value="local-user" autocomplete="off"></label><label>Chat ID<input id="chat" value="local-chat" autocomplete="off"></label>
<label class="wide">Channel Token<input id="token" type="password" autocomplete="off"></label><button id="connect" type="button">连接</button></section>
<section id="timeline" class="timeline" aria-live="polite"><div class="empty">连接后可输入“创建一条标题为验收、内容为 WebUI durable confirmation 的笔记”，验证危险工具的批准、拒绝与恢复链路。</div></section>
<form id="composer"><textarea id="text" rows="2" maxlength="32768" placeholder="输入消息，或创建一条笔记验证 durable confirmation…" required></textarea><button type="submit">发送</button></form>
</main><script src="/webui/app.js" defer></script></body></html>`

const webUICSS = `:root{color-scheme:dark;--bg:#0c1017;--panel:#141b25;--line:#273244;--ink:#eef4ff;--muted:#8fa0b8;--accent:#79e0c3;--accent2:#90b4ff;--danger:#ff9d9d}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#17283b 0,transparent 38%),var(--bg);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif}main{width:min(960px,calc(100% - 28px));margin:28px auto;display:grid;gap:16px}header,.settings,.timeline,form{border:1px solid var(--line);background:color-mix(in srgb,var(--panel) 92%,transparent);border-radius:18px;box-shadow:0 18px 55px #0005}header{display:flex;justify-content:space-between;align-items:center;padding:22px 26px}h1{font-size:34px;line-height:1;margin:7px 0 0;letter-spacing:-.04em}.eyebrow{font:700 11px/1 ui-monospace,monospace;color:var(--accent);letter-spacing:.15em}.status{padding:7px 11px;border:1px solid var(--line);border-radius:999px;color:var(--muted)}.status.ok{border-color:#347865;color:var(--accent)}.settings{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:18px}.settings label{display:grid;gap:6px;color:var(--muted);font-size:12px}.settings .wide{grid-column:1/-1}input,textarea{width:100%;border:1px solid var(--line);border-radius:11px;background:#0b111a;color:var(--ink);padding:11px 12px;font:inherit;outline:none}input:focus,textarea:focus{border-color:var(--accent2)}button{border:0;border-radius:11px;background:var(--accent);color:#06251d;padding:11px 18px;font-weight:800;cursor:pointer}button:disabled{cursor:not-allowed;opacity:.45}.settings button{grid-column:1/-1}.timeline{min-height:390px;max-height:58vh;overflow:auto;padding:20px;display:flex;flex-direction:column;gap:12px}.empty{margin:auto;color:var(--muted);text-align:center}.bubble{max-width:78%;padding:11px 14px;border-radius:15px;background:#202b3a;white-space:pre-wrap;overflow-wrap:anywhere}.bubble.me{align-self:flex-end;background:#254b48}.bubble.confirmation{border:1px solid #71564d;background:#2b2425}.bubble .meta{display:block;margin-top:6px;color:var(--muted);font:10px/1.3 ui-monospace,monospace}.confirmation-state{margin-top:8px;color:var(--muted);font-size:12px}.confirmation-actions{display:flex;gap:8px;margin-top:11px}.confirmation-actions button{padding:8px 13px}.confirmation-actions .deny{background:#5a3034;color:#ffdfe1}form{display:grid;grid-template-columns:1fr auto;gap:12px;padding:14px}textarea{resize:vertical;min-height:52px}@media(max-width:640px){main{margin:14px auto}.settings{grid-template-columns:1fr}.settings .wide{grid-column:auto}.bubble{max-width:92%}header{padding:18px}h1{font-size:28px}}`

const webUIJS = `const $=id=>document.getElementById(id);let connected=false,timer=null,progressAbort=null,seen=new Set(),confirmationViews=new Map(),progressViews=new Map();
const enc=new TextEncoder();async function sign(token,timestamp,nonce,payload){const key=await crypto.subtle.importKey('raw',enc.encode(token),{name:'HMAC',hash:'SHA-256'},false,['sign']);const data=enc.encode(timestamp+'\n'+nonce+'\n'+payload);const out=new Uint8Array(await crypto.subtle.sign('HMAC',key,data));return [...out].map(x=>x.toString(16).padStart(2,'0')).join('')}
function config(){return{route:$('route').value.trim(),account:$('account').value.trim(),user:$('user').value.trim(),chat:$('chat').value.trim(),token:$('token').value}}
function valid(c){return c.route&&c.account&&c.user&&c.chat&&c.token.length>=16}
function add(kind,text,meta,id){if(id&&seen.has(id))return null;if(id)seen.add(id);document.querySelector('.empty')?.remove();const el=document.createElement('div');el.className='bubble '+kind;const body=document.createElement('span');body.textContent=text;el.appendChild(body);const small=document.createElement('span');small.className='meta';small.textContent=meta;el.appendChild(small);$('timeline').appendChild(el);$('timeline').scrollTop=$('timeline').scrollHeight;return{el,body,meta:small}}
async function signedHeaders(c,payload){const timestamp=Math.floor(Date.now()/1000).toString(),nonce=crypto.randomUUID();return{'X-WebUI-Timestamp':timestamp,'X-WebUI-Nonce':nonce,'X-WebUI-Signature':await sign(c.token,timestamp,nonce,payload)}}
function stateLabel(state){return({pending:'等待你的决定',approved:'已批准',denied:'已拒绝',expired:'已过期',consumed:'已执行'})[state]||state}
function addConfirmation(item){const value=item.confirmation,known=confirmationViews.get(item.provider_message_id);if(known){known.state.textContent=stateLabel(value.state)+' · 到期 '+new Date(value.expires_at).toLocaleString();if(value.state!=='pending'&&known.actions?.isConnected)known.actions.remove();return}const view=add('bot confirmation','危险工具确认：'+value.tool_id,item.request_id,item.provider_message_id);if(!view)return;const el=view.el,state=document.createElement('div');state.className='confirmation-state';state.textContent=stateLabel(value.state)+' · 到期 '+new Date(value.expires_at).toLocaleString();el.appendChild(state);if(value.state!=='pending'){confirmationViews.set(item.provider_message_id,{state});return}const actions=document.createElement('div');actions.className='confirmation-actions';const approve=document.createElement('button'),deny=document.createElement('button');approve.type=deny.type='button';approve.textContent='批准一次';deny.textContent='拒绝';deny.className='deny';actions.append(approve,deny);el.appendChild(actions);confirmationViews.set(item.provider_message_id,{state,actions});const decide=async decision=>{approve.disabled=deny.disabled=true;const c=config(),q=new URLSearchParams({route_key:c.route}),uri='/webui/api/confirmations/actions?'+q,body=JSON.stringify({schema_version:1,confirmation_id:value.confirmation_id,expected_version:value.version,decision,external_user_id:c.user,external_chat_id:c.chat});try{const headers=await signedHeaders(c,'POST\n'+uri+'\n'+body);headers['Content-Type']='application/json';const response=await fetch(uri,{method:'POST',headers,body});if(!response.ok)throw new Error('HTTP '+response.status);const result=await response.json();state.textContent=stateLabel(result.state);actions.remove()}catch(error){approve.disabled=deny.disabled=false;$('status').textContent='确认失败 '+error.message;$('status').classList.remove('ok')}};approve.addEventListener('click',()=>decide('approve'));deny.addEventListener('click',()=>decide('deny'))}
async function poll(){if(!connected)return;const c=config();const q=new URLSearchParams({route_key:c.route,external_user_id:c.user,external_chat_id:c.chat});const uri='/webui/api/replies?'+q;try{const headers=await signedHeaders(c,'GET\n'+uri);const response=await fetch(uri,{headers,cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const body=await response.json();for(const item of body.messages){if(item.confirmation){addConfirmation(item);continue}const view=progressViews.get(item.request_id);if(view){view.body.textContent=item.text;view.meta.textContent=item.request_id;progressViews.delete(item.request_id);seen.add(item.provider_message_id)}else add('bot',item.text,item.request_id,item.provider_message_id)}$('status').textContent='已连接';$('status').classList.add('ok')}catch(error){$('status').textContent='读取失败 '+error.message;$('status').classList.remove('ok')}}
async function streamProgress(){const c=config(),q=new URLSearchParams({route_key:c.route,external_user_id:c.user,external_chat_id:c.chat}),uri='/webui/api/progress?'+q,controller=new AbortController();progressAbort=controller;try{const headers=await signedHeaders(c,'GET\n'+uri),response=await fetch(uri,{headers,cache:'no-store',signal:controller.signal});if(!response.ok)throw new Error('HTTP '+response.status);const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';for(;;){const value=await reader.read();if(value.done)break;pending+=decoder.decode(value.value,{stream:true});let boundary;while((boundary=pending.indexOf('\n\n'))>=0){const frame=pending.slice(0,boundary);pending=pending.slice(boundary+2);const data=frame.split('\n').find(line=>line.startsWith('data: '));if(!data)continue;const update=JSON.parse(data.slice(6));if(update.kind==='run.started'){if(!progressViews.has(update.request_id))progressViews.set(update.request_id,add('bot','',update.request_id,'progress:'+update.request_id));continue}if(update.kind==='message.delta'){let view=progressViews.get(update.request_id);if(!view){view=add('bot','',update.request_id,'progress:'+update.request_id);progressViews.set(update.request_id,view)}view.body.textContent+=update.content;$('timeline').scrollTop=$('timeline').scrollHeight}}}}catch(error){if(connected&&!controller.signal.aborted)setTimeout(streamProgress,1000)}}
$('connect').addEventListener('click',()=>{const c=config();if(!valid(c)){alert('请填写完整配置，Token 至少 16 字符');return}progressAbort?.abort();connected=true;seen.clear();confirmationViews.clear();progressViews.clear();$('timeline').replaceChildren();$('status').textContent='连接中';clearInterval(timer);poll();streamProgress();timer=setInterval(poll,1000)});
$('composer').addEventListener('submit',async event=>{event.preventDefault();const c=config(),text=$('text').value.trim();if(!connected||!valid(c)||!text)return;const id=crypto.randomUUID(),occurred=new Date().toISOString();const body=JSON.stringify({schema_version:1,external_account_id:c.account,external_message_id:id,external_user_id:c.user,external_chat_id:c.chat,conversation_type:'p2p',message_type:'text',text,occurred_at:occurred});try{const headers=await signedHeaders(c,body);headers['Content-Type']='application/json';const response=await fetch('/webui/api/messages?route_key='+encodeURIComponent(c.route),{method:'POST',headers,body});if(!response.ok)throw new Error('HTTP '+response.status);add('me',text,id,id);$('text').value='';setTimeout(poll,250)}catch(error){$('status').textContent='发送失败 '+error.message;$('status').classList.remove('ok')}});`
