package bootstrap

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"strings"

	appmodel "github.com/XnLemon/trpc-agent-service/trpcservice/app"
	"github.com/XnLemon/trpc-agent-service/trpcservice/storage/postgres"
	"github.com/XnLemon/trpc-agent-service/trpcservice/tenant"
)

var (
	// ErrInitialization reports a failed first-run initialization operation.
	ErrInitialization = errors.New("initialization failed")
	// ErrInitializationAmbiguous reports a database state that cannot be safely
	// associated with one initial Tenant and Agent App.
	ErrInitializationAmbiguous = errors.New("initialization state is ambiguous")
	// ErrInitializationIncomplete reports a database containing only one side of
	// the initial Tenant and Agent App pair.
	ErrInitializationIncomplete = errors.New("initialization state is incomplete")
	// ErrInitializationAuthorization reports that the explicit operator
	// confirmation required by the init command was not supplied.
	ErrInitializationAuthorization = errors.New("initialization requires explicit authorization")
)

const initialTenantLock = "SELECT pg_advisory_xact_lock(hashtextextended('trpc-agent-service:first-tenant', 0))"

// InitConfig contains the operator-selected metadata for the initial Tenant
// and Agent App. Both database identities are generated by the domain
// constructors and cannot be supplied by the caller.
type InitConfig struct {
	TenantKey         string
	TenantDisplayName string
	AppKey            string
	AppDisplayName    string
	AppDescription    string
}

// InitResult identifies the initial Tenant and Agent App. Created is true only
// when this invocation created both records; a false value means an existing,
// complete initialization was detected.
type InitResult struct {
	TenantID string
	AppID    string
	Created  bool
}

type initialApp struct {
	tenantID string
	appID    string
}

type initialState struct {
	tenants []string
	apps    []initialApp
}

// Validate checks the operator-provided initialization metadata without
// connecting to a database. It does not accept or validate database
// identities, which remain generated by Initialize.
func (config InitConfig) Validate() error {
	_, _, err := newInitialEntities(config)
	return err
}

// Initialize applies the first-run Tenant and Agent App transaction to an
// already migrated PostgreSQL database. It serializes all callers with the
// same database advisory lock used by the first-tenant Admin boundary.
//
// An empty control plane is initialized with one active Tenant and one draft
// Agent App. A database containing exactly one Tenant and one Agent App is
// treated as already initialized. Multiple roots or a partial pair fail closed
// because selecting an existing object would guess the operator's intent.
func Initialize(ctx context.Context, db *sql.DB, config InitConfig) (InitResult, error) {
	if ctx == nil {
		return InitResult{}, ErrInvalidConfig
	}
	if err := ctx.Err(); err != nil {
		return InitResult{}, err
	}
	if db == nil {
		return InitResult{}, ErrInitialization
	}
	tenantRoot, app, err := newInitialEntities(config)
	if err != nil {
		return InitResult{}, err
	}

	tx, err := postgres.Begin(ctx, db)
	if err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	defer postgres.Rollback(tx)
	if _, err := tx.ExecContext(ctx, initialTenantLock); err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	state, err := readInitialState(ctx, tx)
	if err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	return completeInitialization(ctx, tx, state, tenantRoot, app)
}

func completeInitialization(ctx context.Context, tx *sql.Tx, state initialState, tenantRoot *tenant.Tenant, app *appmodel.App) (InitResult, error) {
	if len(state.tenants) > 1 || len(state.apps) > 1 {
		return InitResult{}, initializationStateError(ErrInitializationAmbiguous)
	}
	if len(state.tenants) == 0 && len(state.apps) != 0 {
		return InitResult{}, initializationStateError(ErrInitializationAmbiguous)
	}
	if len(state.tenants) == 0 {
		return createInitialPair(ctx, tx, tenantRoot, app)
	}
	if len(state.apps) == 0 {
		return InitResult{}, initializationStateError(ErrInitializationIncomplete)
	}
	if state.apps[0].tenantID != state.tenants[0] {
		return InitResult{}, initializationStateError(ErrInitializationAmbiguous)
	}
	if err := ctx.Err(); err != nil {
		return InitResult{}, err
	}
	return InitResult{TenantID: state.tenants[0], AppID: state.apps[0].appID}, nil
}

func createInitialPair(ctx context.Context, tx *sql.Tx, tenantRoot *tenant.Tenant, app *appmodel.App) (InitResult, error) {
	if err := createInitialTenant(ctx, tx, tenantRoot); err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	if err := createInitialApp(ctx, tx, app); err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	if err := verifyInitialPair(ctx, tx, tenantRoot.TenantID, app.AppID); err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	if err := postgres.Commit(ctx, tx); err != nil {
		return InitResult{}, mapInitializationDBError(ctx, err)
	}
	return InitResult{TenantID: tenantRoot.TenantID, AppID: app.AppID, Created: true}, nil
}

func newInitialEntities(config InitConfig) (*tenant.Tenant, *appmodel.App, error) {
	tenantRoot, err := tenant.NewTenant(tenant.CreateInput{
		TenantKey:          config.TenantKey,
		DisplayName:        config.TenantDisplayName,
		Status:             tenant.StatusActive,
		AuditRetentionDays: 90,
		LogMaskingLevel:    tenant.MaskingBasic,
		TraceSamplingRate:  1,
	})
	if err != nil {
		return nil, nil, fmt.Errorf("%w: invalid tenant initialization configuration", ErrInvalidConfig)
	}
	app, err := appmodel.NewApp(appmodel.CreateInput{
		TenantID:    tenantRoot.TenantID,
		AppKey:      config.AppKey,
		DisplayName: config.AppDisplayName,
		Description: config.AppDescription,
	})
	if err != nil {
		return nil, nil, fmt.Errorf("%w: invalid agent app initialization configuration", ErrInvalidConfig)
	}
	return tenantRoot, app, nil
}

func readInitialTenants(ctx context.Context, tx *sql.Tx) ([]string, error) {
	rows, err := tx.QueryContext(ctx, "SELECT tenant_id FROM public.tenant ORDER BY tenant_id LIMIT 2")
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	values := make([]string, 0, 2)
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		values = append(values, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return values, nil
}

func readInitialApps(ctx context.Context, tx *sql.Tx) ([]initialApp, error) {
	rows, err := tx.QueryContext(ctx, "SELECT tenant_id, app_id FROM public.agent_app ORDER BY tenant_id, app_id LIMIT 2")
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	values := make([]initialApp, 0, 2)
	for rows.Next() {
		var value initialApp
		if err := rows.Scan(&value.tenantID, &value.appID); err != nil {
			return nil, err
		}
		values = append(values, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return values, nil
}

func readInitialState(ctx context.Context, tx *sql.Tx) (initialState, error) {
	tenants, err := readInitialTenants(ctx, tx)
	if err != nil {
		return initialState{}, err
	}
	apps, err := readInitialApps(ctx, tx)
	if err != nil {
		return initialState{}, err
	}
	return initialState{tenants: tenants, apps: apps}, nil
}

func createInitialTenant(ctx context.Context, tx *sql.Tx, value *tenant.Tenant) error {
	_, err := tx.ExecContext(ctx, `
		SELECT public.control_plane_create_tenant(
			$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
		)`,
		value.TenantID, value.TenantKey, value.DisplayName, string(value.Status),
		value.RateLimitRPM, value.MaxConcurrentExecutions, value.MonthlyTokenBudget,
		value.MonthlySpendLimitMinor, nullableInitText(value.BillingCurrency),
		value.AuditRetentionDays, string(value.LogMaskingLevel), value.TraceSamplingRate,
		value.DefaultAgentAppID, value.DefaultBackendProfileID, value.Version,
		value.CreatedAt, value.UpdatedAt,
	)
	return err
}

func createInitialApp(ctx context.Context, tx *sql.Tx, value *appmodel.App) error {
	_, err := tx.ExecContext(ctx, `
		SELECT public.control_plane_create_agent_app(
			$1, $2, $3, $4, $5, $6, $7, $8, $9
		)`,
		value.TenantID, value.AppID, value.AppKey, value.DisplayName, value.Description,
		string(value.Status), value.Version, value.CreatedAt, value.UpdatedAt,
	)
	return err
}

func verifyInitialPair(ctx context.Context, tx *sql.Tx, tenantID, appID string) error {
	var present int
	err := tx.QueryRowContext(ctx, `
		SELECT 1
		FROM public.agent_app
		WHERE tenant_id = $1 AND app_id = $2
	`, tenantID, appID).Scan(&present)
	return err
}

func nullableInitText(value string) any {
	if strings.TrimSpace(value) == "" {
		return nil
	}
	return value
}

func initializationStateError(kind error) error {
	return fmt.Errorf("%w: %w", ErrInitialization, kind)
}

func mapInitializationDBError(ctx context.Context, err error) error {
	if err == nil {
		return nil
	}
	if ctx != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return ctxErr
		}
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return err
	}
	return fmt.Errorf("%w: database operation failed", ErrInitialization)
}

// WriteInitResult writes the only operator configuration produced by init: a
// shell-compatible pair of generated IDs. It deliberately omits the DSN,
// metadata, and every credential or secret.
func WriteInitResult(w io.Writer, result InitResult) error {
	if w == nil || !validInitOutputID(result.TenantID, "t_") || !validInitOutputID(result.AppID, "app_") {
		return ErrInitialization
	}
	if result.Created {
		_, err := fmt.Fprintln(w, "# trpc-service init created the initial Tenant and Agent App")
		if err != nil {
			return err
		}
	} else {
		_, err := fmt.Fprintln(w, "# trpc-service init found the existing initial Tenant and Agent App")
		if err != nil {
			return err
		}
	}
	_, err := fmt.Fprintf(w, "export TRPC_TENANT_ID='%s'\nexport TRPC_APP_ID='%s'\n", result.TenantID, result.AppID)
	return err
}

func validInitOutputID(value, prefix string) bool {
	if !strings.HasPrefix(value, prefix) || len(value) != len(prefix)+26 {
		return false
	}
	payload := value[len(prefix):]
	if payload[0] > '7' {
		return false
	}
	for _, character := range payload {
		if !strings.ContainsRune("0123456789ABCDEFGHJKMNPQRSTVWXYZ", character) {
			return false
		}
	}
	return true
}
