"use client";

import { Plus, RefreshCw } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ApiNotice, Button, Drawer, EmptyState, Field, PageHeader, StatCard, StatusBadge } from "../../../components/ui";
import { controlApi, type User } from "../../../lib/control-api";

export default function UsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [total, setTotal] = useState(0); const [offset, setOffset] = useState(0); const [query, setQuery] = useState(""); const [drawer, setDrawer] = useState(false); const [error, setError] = useState<unknown>(); const limit = 20;
  const load = useCallback(() => { setError(undefined); return controlApi.listUsers({ offset, limit }).then((result) => { setUsers(result.users); setTotal(result.total); }).catch(setError); }, [offset]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => users.filter((user) => `${user.username} ${user.display_name}`.toLowerCase().includes(query.toLowerCase())), [query, users]);
  return <><PageHeader eyebrow="IDENTITY" title="平台用户" description="管理平台账号和临时登录凭据。" action={<Button onClick={() => setDrawer(true)}><Plus size={15}/>创建用户</Button>} /><ApiNotice error={error}/><div className="stats-grid"><StatCard detail="数据库中的全部账号" label="用户总数" value={total}/><StatCard detail="当前页可用账号" label="ACTIVE" value={users.filter((u)=>u.status === "ACTIVE").length}/><StatCard detail="新账号首次登录后必须修改密码" label="凭据策略" value="临时密码"/></div><div className="panel"><div className="toolbar"><input aria-label="搜索用户" className="search" onChange={(e)=>setQuery(e.target.value)} placeholder="搜索用户名或显示名称" value={query}/><Button onClick={()=>void load()} variant="secondary"><RefreshCw size={14}/>刷新</Button></div>{visible.length === 0 ? <EmptyState detail="创建第一个平台账号，或调整搜索条件。" title="没有找到用户"/> : <div className="table-wrap"><table><thead><tr><th>用户</th><th>用户名</th><th>状态</th><th>创建时间</th></tr></thead><tbody>{visible.map((user)=><tr key={user.id}><td><div className="cell-primary"><span className="mini-avatar">{user.display_name.slice(0,2).toUpperCase()}</span><strong>{user.display_name}</strong></div></td><td>{user.username}</td><td><StatusBadge tone={user.status === "ACTIVE" ? "green" : "gray"}>{user.status ?? "ACTIVE"}</StatusBadge></td><td>{formatTime(user.created_at)}</td></tr>)}</tbody></table></div>}<div className="pagination"><span>共 {total} 条</span><div className="pagination-actions"><Button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))} variant="secondary">上一页</Button><Button disabled={offset+limit>=total} onClick={()=>setOffset(offset+limit)} variant="secondary">下一页</Button></div></div></div>{drawer&&<CreateUserDrawer onClose={()=>setDrawer(false)} onCreated={()=>{setDrawer(false);void load();}}/>}</>;
}

function CreateUserDrawer({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}) { const [username,setUsername]=useState("");const [displayName,setDisplayName]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError(undefined);try{await controlApi.createUser({username,display_name:displayName,temporary_password:password});onCreated();}catch(caught){setError(caught);}finally{setBusy(false);}}return <Drawer description="用户首次登录后必须修改临时密码。" onClose={onClose} title="创建用户"><form className="form-stack" onSubmit={(event)=>void submit(event)}><ApiNotice error={error}/><Field label="用户名" onChange={(e)=>setUsername(e.target.value)} required value={username}/><Field label="显示名称" onChange={(e)=>setDisplayName(e.target.value)} required value={displayName}/><Field hint="至少 12 位" label="临时密码" onChange={(e)=>setPassword(e.target.value)} required type="password" value={password}/><div className="form-actions"><Button onClick={onClose} type="button" variant="secondary">取消</Button><Button disabled={busy} type="submit">{busy?"正在创建…":"创建"}</Button></div></form></Drawer>}
function formatTime(value?:string){return value?new Date(value).toLocaleString("zh-CN") : "—"}
