"use client";

import { Plus } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ApiNotice, Button, Drawer, EmptyState, Field, PageHeader, StatCard, StatusBadge } from "../../../components/ui";
import { controlApi, type Tenant } from "../../../lib/control-api";

export default function AdminTenantsPage(){const[items,setItems]=useState<Tenant[]>([]);const[total,setTotal]=useState(0);const[offset,setOffset]=useState(0);const[error,setError]=useState<unknown>();const[drawer,setDrawer]=useState(false);const limit=20;const load=useCallback(()=>controlApi.listAdminTenants({offset,limit}).then((r)=>{setItems(r.tenants);setTotal(r.total)}).catch(setError),[offset]);useEffect(()=>{void load()},[load]);return <><PageHeader eyebrow="TENANT PROVISIONING" title="租户" description="开通租户并指定初始 Owner。" action={<Button onClick={()=>setDrawer(true)}><Plus size={15}/>创建租户</Button>}/><ApiNotice error={error}/><div className="stats-grid"><StatCard detail="平台中的全部租户" label="租户总数" value={total}/><StatCard detail="当前页激活租户" label="ACTIVE" value={items.filter((t)=>t.status==="ACTIVE").length}/><StatCard detail="每个租户必须指定初始 Owner" label="所有权" value="Required"/></div><div className="panel">{items.length===0?<EmptyState detail="创建第一个租户并指定初始 Owner。" title="没有租户"/>:<div className="table-wrap"><table><thead><tr><th>租户</th><th>Slug</th><th>状态</th><th>创建时间</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.slug}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>{new Date(item.created_at).toLocaleString("zh-CN")}</td></tr>)}</tbody></table></div>}<div className="pagination"><span>共 {total} 条</span><div className="pagination-actions"><Button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))} variant="secondary">上一页</Button><Button disabled={offset+limit>=total} onClick={()=>setOffset(offset+limit)} variant="secondary">下一页</Button></div></div></div>{drawer&&<CreateTenantDrawer onClose={()=>setDrawer(false)} onDone={()=>{setDrawer(false);void load()}}/>}</>}
function CreateTenantDrawer({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const[slug,setSlug]=useState("");const[name,setName]=useState("");const[owner,setOwner]=useState("");const[error,setError]=useState<unknown>();async function submit(e:FormEvent){e.preventDefault();try{await controlApi.createTenant({slug,name,owner_user_id:owner});onDone()}catch(caught){setError(caught)}}return <Drawer description="创建租户时会同时建立 OWNER Membership。" onClose={onClose} title="创建租户"><form className="form-stack" onSubmit={(e)=>void submit(e)}><ApiNotice error={error}/><Field label="租户 Slug" onChange={(e)=>setSlug(e.target.value)} placeholder="team-a" required value={slug}/><Field label="租户名称" onChange={(e)=>setName(e.target.value)} required value={name}/><Field label="初始 Owner 用户 ID" onChange={(e)=>setOwner(e.target.value)} required value={owner}/><div className="form-actions"><Button onClick={onClose} type="button" variant="secondary">取消</Button><Button type="submit">创建</Button></div></form></Drawer>}
