// Command generate derives wire DTOs from the canonical JSON Schema. The schema
// remains authoritative for conditional required fields and numeric bounds.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type schema struct {
	Title       string            `json:"title"`
	Type        string            `json:"type"`
	Ref         string            `json:"$ref"`
	GoType      string            `json:"x-go-type"`
	Required    []string          `json:"required"`
	Properties  map[string]schema `json:"properties"`
	Definitions map[string]schema `json:"$defs"`
	Items       *schema           `json:"items"`
}

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	data, err := os.ReadFile("route-projected.schema.json")
	if err != nil {
		return err
	}
	var root schema
	if err = json.Unmarshal(data, &root); err != nil {
		return err
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by api/events/control/v1/generate from route-projected.schema.json; DO NOT EDIT.")
	fmt.Fprintln(&out, "package controlv1")
	fmt.Fprintf(&out, "\nconst RouteProjectionSchemaSHA256 = %q\n", fmt.Sprintf("%x", sha256.Sum256(data)))
	names := make([]string, 0, len(root.Definitions))
	for name := range root.Definitions {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err = emit(&out, name, root.Definitions[name]); err != nil {
			return err
		}
	}
	if err = emit(&out, root.Title, root); err != nil {
		return err
	}
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	dest := filepath.Join("..", "..", "..", "..", "gen", "events", "control", "v1", "route_projected.gen.go")
	if err = os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return err
	}
	return os.WriteFile(dest, formatted, 0644)
}

func emit(out *bytes.Buffer, name string, object schema) error {
	if object.Type != "object" {
		return fmt.Errorf("%s: expected object schema", name)
	}
	fmt.Fprintf(out, "\ntype %s struct {\n", name)
	fields := make([]string, 0, len(object.Properties))
	for field := range object.Properties {
		fields = append(fields, field)
	}
	sort.Strings(fields)
	for _, field := range fields {
		property := object.Properties[field]
		required := false
		for _, item := range object.Required {
			if item == field {
				required = true
			}
		}
		typ := property.GoType
		if strings.HasPrefix(property.Ref, "#/$defs/") {
			typ = strings.TrimPrefix(property.Ref, "#/$defs/")
			if !required {
				typ = "*" + typ
			}
		}
		if typ == "" {
			switch property.Type {
			case "string":
				typ = "string"
			case "boolean":
				typ = "bool"
			case "integer":
				typ = "int64"
			case "array":
				if property.Items == nil || property.Items.Type != "string" {
					return fmt.Errorf("unsupported array schema for %s.%s", name, field)
				}
				typ = "[]string"
			default:
				return fmt.Errorf("unsupported schema type for %s.%s", name, field)
			}
		}
		if typ != "string" && typ != "bool" && typ != "int" && typ != "int64" && typ != "[]string" && property.Ref == "" {
			return fmt.Errorf("unsupported Go type %q", typ)
		}
		tag := field
		if !required {
			tag += ",omitempty"
		}
		fmt.Fprintf(out, "%s %s `json:%q`\n", goName(field), typ, tag)
	}
	fmt.Fprintln(out, "}")
	return nil
}

func goName(field string) string {
	parts := strings.Split(field, "_")
	for i, part := range parts {
		if part == "id" {
			parts[i] = "ID"
		} else {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
