import { useEffect, useState, type FormEvent } from "react";
import { Play, Plug, Plus, Trash2, X } from "lucide-react";
import { api, type APIError, type AgentApp, type BotRoute, type ChannelBinding, type Identity, type ProviderDelivery, type ProviderStatus } from "./api";
import { AsyncState } from "./AsyncState";

export function ChannelsPage({ identity }: { identity: Identity }) {
  const [items, setItems] = useState<ChannelBinding[]>();
  const [apps, setApps] = useState<AgentApp[]>([]);
  const [providers, setProviders] = useState<ProviderStatus[]>([]);
  const [routes, setRoutes] = useState<BotRoute[]>([]);
  const [deliveries, setDeliveries] = useState<ProviderDelivery[]>([]);
  const [error, setError] = useState<APIError>();
  const [channel, setChannel] = useState<BotRoute["provider"]>("enterprise_wechat");
  const [appID, setAppID] = useState("");
  const [conversation, setConversation] = useState("");
  const [replayRoute, setReplayRoute] = useState<BotRoute>();
  const [replayText, setReplayText] = useState("");
  const [replayStatus, setReplayStatus] = useState("");
  const mutable = ["platform_admin", "tenant_admin", "operator"].includes(identity.active_role);
  const load = () => { setError(undefined); void Promise.all([api.bindings(), api.apps(), api.providerStatuses(), api.providerRoutes(), api.providerDeliveries()]).then(([bindings, appResult, providerResult, routeResult, deliveryResult]) => { setItems(bindings.items); setApps(appResult.items); setProviders(providerResult.items); setRoutes(routeResult.items); setDeliveries(deliveryResult.items); setAppID((current) => current || appResult.items[0]?.id || ""); }).catch((caught) => setError(caught as APIError)); };
  useEffect(load, [identity.active_tenant_id]);
  const create = async (event: FormEvent) => { event.preventDefault(); if (identity.active_role !== "platform_admin" || !appID || !conversation) return; try { await api.createProviderRoute({ provider: channel, external_subject: conversation, tenant_id: identity.active_tenant_id, app_id: appID, conversation_type: "single", enabled: true }); setConversation(""); load(); } catch (caught) { setError(caught as APIError); } };
  if (!items) return <AsyncState kind="loading" />;
  const toggle = async (binding: ChannelBinding) => { try { await api.setBindingEnabled(binding.id, !binding.enabled); load(); } catch (caught) { setError(caught as APIError); } };
  const remove = async (id: string) => { try { await api.deleteBinding(id); load(); } catch (caught) { setError(caught as APIError); } };
  const toggleRoute = async (route: BotRoute) => { const next = { ...route, enabled: !route.enabled }; setRoutes((current) => current.map((item) => item.provider === route.provider && item.external_subject === route.external_subject ? next : item)); try { await api.updateProviderRoute(next); load(); } catch (caught) { setError(caught as APIError); load(); } };
  const removeRoute = async (route: BotRoute) => { try { await api.deleteProviderRoute(route); load(); } catch (caught) { setError(caught as APIError); } };
  const replay = async (event: FormEvent) => { event.preventDefault(); if (!replayRoute || !replayText.trim()) return; try { const result = await api.replayProviderRoute(replayRoute, replayText); setReplayStatus(`Replay 已接受：${result.request_id}`); setReplayRoute(undefined); setReplayText(""); for (let attempt = 0; attempt < 20; attempt += 1) { const next = (await api.providerDeliveries()).items; setDeliveries(next); const delivery = next.find((item) => item.request_id === result.request_id); if (delivery && delivery.status !== "accepted") break; await new Promise((resolve) => window.setTimeout(resolve, 100)); } } catch (caught) { setError(caught as APIError); } };
  return <div className="channels-page">
    {error && <div className="inline-error">{error.message}</div>}
    <div className="runtime-grid">{providers.map((provider) => <div className="runtime-item" key={provider.provider}><div className="runtime-title"><Plug aria-hidden="true" /><div><h3>{provider.provider}</h3><span>Provider Account</span><small>凭据 Smoke：{provider.credential_smoke_status}</small></div><span className={`status ${provider.status === "connected" ? "healthy" : "paused"}`}>{provider.status}</span></div></div>)}</div>
    <form className="channel-form" onSubmit={(event) => void create(event)}>
      <label>Provider<select value={channel} onChange={(event) => setChannel(event.target.value as BotRoute["provider"])} disabled={!mutable}><option value="enterprise_wechat">企业微信</option><option value="telegram">Telegram</option></select></label>
      <label>Agent 应用<select value={appID} onChange={(event) => setAppID(event.target.value)} disabled={!mutable}>{apps.map((app) => <option value={app.id} key={app.id}>{app.name}</option>)}</select></label>
      <label>会话 ID<input value={conversation} onChange={(event) => setConversation(event.target.value)} disabled={!mutable} /></label>
      <button className="primary" type="submit" disabled={identity.active_role !== "platform_admin" || !appID || !conversation}><Plus aria-hidden="true" />创建路由</button>
    </form>
    {replayStatus && <div role="status" className="inline-success">{replayStatus}</div>}
    {routes.length > 0 && <div className="table-wrap"><table><thead><tr><th>Bot Provider</th><th>Provider Account</th><th>外部会话</th><th>Tenant</th><th>Agent App</th><th>状态</th><th>最近投递</th><th>操作</th></tr></thead><tbody>{routes.map((route) => { const delivery = deliveries.find((item) => item.provider === route.provider && item.external_subject === route.external_subject); return <tr key={`${route.provider}:${route.provider_account ?? ""}:${route.external_subject}`}><td><Plug aria-hidden="true" />{route.provider}</td><td>{route.provider_account ?? "-"}</td><td>{route.external_subject}</td><td>{route.tenant_id}</td><td>{route.app_id}</td><td><span className={`status ${route.enabled ? "active" : "paused"}`}>{route.enabled ? "启用" : "停用"}</span></td><td><span className={`status ${delivery?.status === "delivered" ? "healthy" : "paused"}`}>{delivery?.status ?? "-"}</span>{delivery?.request_id && <small>{delivery.request_id}</small>}</td><td><input type="checkbox" aria-label={`${route.external_subject} 路由启用状态`} checked={route.enabled} onChange={() => void toggleRoute(route)} disabled={identity.active_role !== "platform_admin"} /><button className="icon-button" title="重放测试消息" aria-label={`重放 ${route.external_subject} 测试消息`} onClick={() => { setReplayRoute(route); setReplayStatus(""); }} disabled={identity.active_role !== "platform_admin" || !route.enabled}><Play aria-hidden="true" /></button><button className="icon-button" title="删除路由" aria-label={`删除 ${route.external_subject} 路由`} onClick={() => void removeRoute(route)} disabled={identity.active_role !== "platform_admin"}><Trash2 aria-hidden="true" /></button></td></tr>; })}</tbody></table></div>}
    {deliveries.length > 0 && <div className="table-wrap"><table><thead><tr><th>Provider</th><th>外部会话</th><th>Request</th><th>投递结果</th><th>错误码</th><th>次数</th></tr></thead><tbody>{deliveries.map((delivery) => <tr key={`${delivery.provider}:${delivery.external_subject}:${delivery.request_id}`}><td>{delivery.provider}</td><td>{delivery.external_subject}</td><td><small>{delivery.request_id}</small></td><td><span className={`status ${delivery.status === "delivered" ? "healthy" : "paused"}`}>{delivery.status}</span></td><td>{delivery.code ?? "-"}</td><td>{delivery.attempts}</td></tr>)}</tbody></table></div>}
    <div className="table-wrap"><table><thead><tr><th>Provider</th><th>会话</th><th>用户</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map((binding) => <tr key={binding.id}><td><Plug aria-hidden="true" />{binding.channel}</td><td>{binding.external_conversation_id}</td><td>{binding.external_user_id}</td><td><span className={`status ${binding.enabled ? "active" : "paused"}`}>{binding.enabled ? "启用" : "停用"}</span></td><td><button className="icon-button" title={binding.enabled ? "停用" : "启用"} onClick={() => void toggle(binding)} disabled={!mutable}>{binding.enabled ? "停用" : "启用"}</button><button className="icon-button" title="删除" onClick={() => void remove(binding.id)} disabled={!mutable}><Trash2 aria-hidden="true" /></button></td></tr>)}</tbody></table></div>
    {replayRoute && <div className="modal-backdrop"><form className="modal" onSubmit={(event) => void replay(event)}><div className="modal-title"><h3>重放测试消息</h3><button type="button" className="icon-button" title="关闭" onClick={() => setReplayRoute(undefined)}><X aria-hidden="true" /></button></div><label>消息内容<textarea value={replayText} onChange={(event) => setReplayText(event.target.value)} rows={4} maxLength={2048} required /></label><div className="form-actions"><button type="button" onClick={() => setReplayRoute(undefined)}>取消</button><button className="primary" type="submit" disabled={!replayText.trim()}><Play aria-hidden="true" />重放</button></div></form></div>}
  </div>;
}
