#!/usr/bin/env bash
# Canary / blue-green rollout of the PLATFORM version.
#
#   bash scripts/canary.sh up                 # build + start the new build (v2)
#   bash scripts/canary.sh weight 10 [tenants] # 10% of traffic, plus pilot tenants
#   bash scripts/canary.sh check [n]          # verify the observed split (default 200 samples)
#   bash scripts/canary.sh status             # current state + /version of both builds
#   bash scripts/canary.sh rollback           # 0% and drain v2 (the fast way back)
#   bash scripts/canary.sh promote            # rebuild the primary service on the new build
#   bash scripts/canary.sh stop               # stop v2 (edge back to 100% old build)
#
# Why this shape: a rollout has to be (a) a config change rather than a
# redeploy, (b) verifiable from outside, and (c) reversible with one command.
# The weight lives in deployments/canary/weight.conf, which this script
# regenerates and the edge nginx reloads; "which build answered" is answered by
# GET /version, so the check is an observation instead of a guess.
#
# The stateful IM gateway is deliberately NOT part of the percentage rollout:
# one bot account can only be held by one process. Move it by blue/green (stop
# the old node's gateway, start the new one) — see docs/部署与运维手册.md.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILES=(-f "$ROOT/deployments/docker-compose.yml" -f "$ROOT/deployments/docker-compose.canary.yml")
WEIGHT_FILE="$ROOT/deployments/canary/weight.conf"
EDGE_PORT="${EDGE_PORT:-5173}"
CANARY_VERSION="${CANARY_VERSION:-v2}"

log() { printf '\033[1;34m[canary]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[canary]\033[0m %s\n' "$*" >&2; exit 1; }

compose() { docker compose "${COMPOSE_FILES[@]}" --project-directory "$ROOT/deployments" "$@"; }

require_docker() {
  command -v docker >/dev/null 2>&1 || die "docker is required"
  docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
}

# write_weight <percent> <comma-separated pilot tenants>
write_weight() {
  local percent="$1" tenants="${2:-}"
  [[ "$percent" =~ ^[0-9]+$ ]] || die "weight must be an integer 0..100"
  (( percent >= 0 && percent <= 100 )) || die "weight must be 0..100"

  local tenant_block="    default 0;"
  if [[ -n "$tenants" ]]; then
    # Anchor the alternation so t-pilot does not also match t-pilot-2.
    local pattern
    pattern="^($(printf '%s' "$tenants" | sed 's/,/|/g'))\$"
    tenant_block="    default 0;
    ~${pattern} 1;"
  fi

  # nginx rejects a 0% entry in split_clients ("invalid percent"), so a fully
  # rolled-back state is expressed by having no percentage entry at all.
  local weight_line="    *  0;"
  if (( percent > 0 )); then
    weight_line="    ${percent}% 1;
    *  0;"
  fi

  cat > "$WEIGHT_FILE" <<EOF
# Generated by scripts/canary.sh — DO NOT EDIT BY HAND.
#
# Current rollout state: v2 weight ${percent}%, pilot tenants: ${tenants:-(none)}
#
# Regenerate with:
#   bash scripts/canary.sh weight ${percent} ${tenants}

# A pilot tenant is pinned to the new build regardless of the weight: that is
# the "make the change visible to people who can report on it" step, and it is
# deterministic enough to explain to a customer.
map \$http_x_tenant_id \$forced_v2 {
${tenant_block}
}

# Everyone else is split by weight. The key is the sticky cookie (set per
# browser) so one user keeps landing on the same build; without it the cookie
# falls back to the client address, which is still stable per client.
split_clients "\${cookie_dsh_uid}\${remote_addr}" \$weighted_v2 {
${weight_line}
}

map "\$forced_v2\$weighted_v2" \$backend_upstream {
    default "backend:8080";
    "10"    "backend-v2:8080";
    "01"    "backend-v2:8080";
    "11"    "backend-v2:8080";
}
EOF
  log "weight.conf: ${percent}% -> ${CANARY_VERSION}${tenants:+, pilot tenants: $tenants}"
}

reload_edge() {
  compose exec -T frontend nginx -t >/dev/null || die "edge config is invalid (see nginx -t)"
  compose exec -T frontend nginx -s reload
  # nginx reloads gracefully: the old workers keep serving in-flight requests
  # while the new ones start. Sampling immediately can therefore observe the
  # PREVIOUS weight (a rollback that still shows a few percent on the canary is
  # this, not a stale route), so give the swap a moment before anyone measures.
  sleep "${RELOAD_SETTLE:-2}"
  log "edge reloaded"
}

# probe <path> — one request through the edge, printing the serving build.
probe() {
  local path="${1:-/api/version}" uid="${2:-}"
  if [[ -n "$uid" ]]; then
    curl -s -H "Cookie: dsh_uid=$uid" "http://127.0.0.1:${EDGE_PORT}${path}"
  else
    curl -s "http://127.0.0.1:${EDGE_PORT}${path}"
  fi
}

cmd_up() {
  require_docker
  write_weight "${CANARY_WEIGHT:-0}" "${CANARY_TENANTS:-}"
  log "building and starting ${CANARY_VERSION} (role=worker, no host port)…"
  compose up -d --build backend-v2 frontend
  log "waiting for ${CANARY_VERSION} to become healthy…"
  for _ in $(seq 1 60); do
    if compose exec -T backend-v2 wget -qO- http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
      log "${CANARY_VERSION} is up"
      cmd_status
      return 0
    fi
    sleep 2
  done
  die "${CANARY_VERSION} did not become healthy; check: docker compose logs backend-v2"
}

cmd_weight() {
  require_docker
  local percent="${1:-}" tenants="${2:-}"
  [[ -n "$percent" ]] || die "usage: canary.sh weight <0..100> [tenant1,tenant2]"
  write_weight "$percent" "$tenants"
  reload_edge
}

# cmd_check samples the edge and reports the observed split. A canary that is
# not measured is just a hope: this is the step that says whether the weight
# actually took effect.
cmd_check() {
  require_docker
  local n="${1:-200}" v1=0 v2=0 other=0 body version
  log "sampling ${n} requests through the edge (:${EDGE_PORT}/api/version)…"
  for i in $(seq 1 "$n"); do
    body="$(probe /api/version "sample-${i}")" || { other=$((other+1)); continue; }
    version="$(printf '%s' "$body" | sed -n 's/.*"version":"\([^"]*\)".*/\1/p')"
    case "$version" in
      "$CANARY_VERSION") v2=$((v2+1)) ;;
      "") other=$((other+1)) ;;
      *) v1=$((v1+1)) ;;
    esac
  done
  printf 'observed: primary=%d  %s=%d  unresolved=%d  (of %d)\n' "$v1" "$CANARY_VERSION" "$v2" "$other" "$n"
  awk -v v2="$v2" -v n="$n" 'BEGIN { printf "observed share of %s: %.1f%%\n", "'"$CANARY_VERSION"'", (n>0 ? v2*100/n : 0) }'
}

cmd_tenant_check() {
  require_docker
  local tenant="${1:-}" n="${2:-20}" hit=0 body version
  [[ -n "$tenant" ]] || die "usage: canary.sh tenant-check <tenant-id> [n]"
  for _ in $(seq 1 "$n"); do
    body="$(curl -s -H "X-Tenant-Id: ${tenant}" -H "Cookie: dsh_uid=$(date +%s%N)" "http://127.0.0.1:${EDGE_PORT}/api/version")"
    version="$(printf '%s' "$body" | sed -n 's/.*"version":"\([^"]*\)".*/\1/p')"
    # An `if` rather than `[[ ]] && …`: under `set -e` the short-circuit form
    # would abort the whole script on the first sample that is NOT the canary.
    if [[ "$version" == "$CANARY_VERSION" ]]; then
      hit=$((hit+1))
    fi
  done
  printf 'tenant %s: %d/%d requests served by %s\n' "$tenant" "$hit" "$n" "$CANARY_VERSION"
}

cmd_status() {
  require_docker
  printf -- '--- edge weights ---\n'
  grep -E '^(# Current|    [0-9]+%|    ~|    default)' "$WEIGHT_FILE" | sed 's/^/    /'
  printf -- '--- serving builds ---\n'
  for svc in backend backend-v2; do
    local info
    info="$(compose exec -T "$svc" wget -qO- http://127.0.0.1:8080/version 2>/dev/null || true)"
    if [[ -n "$info" ]]; then
      printf '    %-12s %s\n' "$svc" "$info"
    else
      printf '    %-12s (not running)\n' "$svc"
    fi
  done
}

cmd_rollback() {
  require_docker
  log "rolling back: 0% to ${CANARY_VERSION}, edge back on the primary build"
  write_weight 0 ""
  reload_edge
  cmd_check "${CHECK_N:-100}"
  log "the ${CANARY_VERSION} container is left running for inspection; stop it with: canary.sh stop"
}

# promote rebuilds the PRIMARY service from the current source and drops the
# canary container: in a real deployment this is "point the base service at the
# new image tag", and the canary service then disappears.
cmd_promote() {
  require_docker
  write_weight 0 ""
  reload_edge
  log "rebuilding the primary service on the new build…"
  compose up -d --build backend
  compose rm -sf backend-v2
  log "promoted: the primary service now runs the new build"
  cmd_status
}

cmd_stop() {
  require_docker
  write_weight 0 ""
  reload_edge
  compose rm -sf backend-v2
  log "${CANARY_VERSION} stopped; the edge serves the primary build only"
}

case "${1:-}" in
  up)           shift; cmd_up "$@" ;;
  weight)       shift; cmd_weight "$@" ;;
  check)        shift; cmd_check "$@" ;;
  tenant-check) shift; cmd_tenant_check "$@" ;;
  status)       shift; cmd_status "$@" ;;
  rollback)     shift; cmd_rollback "$@" ;;
  promote)      shift; cmd_promote "$@" ;;
  stop)         shift; cmd_stop "$@" ;;
  *)
    sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
    ;;
esac
