# Capacity measurement against the running stack (docs/部署与运维手册.md §容量评估).
#
# Every number it prints is measured, not estimated: load is generated by
# cmd/loadtest, datastore load comes from Redis/MySQL's own counters, and host
# cost comes from `docker stats`. Run it against a stack that is otherwise idle,
# and quote the date with the numbers — the values depend on the model endpoint
# behind the platform, which is not under our control.
#
# Usage: pwsh -File scripts/capacity-probe.ps1 [-PublishN 200] [-PublishC 20] [-TurnN 8] [-TurnC 4]
param(
  [string]$Base = "http://127.0.0.1:8080",
  [string]$Tenant = "t-demo",
  [string]$Agent = "agent001",
  [int]$PublishN = 200,
  [int]$PublishC = 20,
  [int]$TurnN = 8,
  [int]$TurnC = 4,
  [string]$BackendContainer = "deployments-backend-1",
  [string]$RedisContainer = "deployments-redis-1",
  [string]$MySQLContainer = "deployments-mysql-1",
  [string]$MySQLUser = "root",
  [string]$MySQLPassword = "trpc123",
  [string]$MySQLDatabase = "trpc_agent_service"
)

$ErrorActionPreference = "Stop"
$env:GOMODCACHE = Join-Path (Get-Location) ".mc8"
$env:GOCACHE = Join-Path (Get-Location) ".gc14"
$env:GOPROXY = "https://goproxy.cn,direct"

function Say([string]$m) { Write-Host $m }
function Sql([string]$q) {
  (docker exec $MySQLContainer mysql "-u$MySQLUser" "-p$MySQLPassword" -N -B -D $MySQLDatabase -e $q 2>$null) -join "`n"
}
function RedisTotal {
  $out = docker exec $RedisContainer redis-cli INFO stats
  [int64](($out | Select-String '^total_commands_processed:').Line -replace '.*:')
}
function MySQLQuestions {
  $out = Sql "SHOW GLOBAL STATUS LIKE 'Questions'"
  [int64](($out -split "`t")[1])
}

$exe = Join-Path $env:TEMP "trpc-loadtest.exe"
go build -o $exe ./cmd/loadtest | Out-Null

Say "# capacity probe $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')"
Say "base=$Base tenant=$Tenant agent=$Agent"

Say ""
Say "## 1. token consumption per turn (usage_records, all history)"
$usage = Sql @"
SELECT dimension, COUNT(*) AS rows_n, ROUND(SUM(amount),1) AS amount
FROM usage_records GROUP BY dimension ORDER BY amount DESC
"@
Say $usage
$avg = Sql "SELECT ROUND(AVG(amount),1), COUNT(*) FROM usage_records WHERE dimension='token' AND amount>0"
$avgParts = $avg -split "`t"
Say "token dimension: avg=$($avgParts[0]) tokens/turn over $($avgParts[1]) turns"
Say "consumer group state: $((docker exec $RedisContainer redis-cli XINFO GROUPS stream:inbound | Select-String 'consumers|pending|lag' | ForEach-Object { $_.Line.Trim() }) -join '  ')"

Say ""
Say "## 2. publish ceiling (POST /chat only: HTTP + rate limit + XADD)"
$r0 = RedisTotal; $q0 = MySQLQuestions; $t0 = Get-Date
if ($PublishN -gt 0) {
  $pub = & $exe -base $Base -tenant $Tenant -agent $Agent -mode publish -n $PublishN -c $PublishC 2>&1 | Out-String
  $pubElapsed = ((Get-Date) - $t0).TotalSeconds
  $r1 = RedisTotal; $q1 = MySQLQuestions
  Say ($pub.Trim())
  Say ("datastore during publish: redis {0:N0} cmd/s, mysql {1:N0} q/s (over {2:N1}s)" -f (($r1 - $r0) / $pubElapsed), (($q1 - $q0) / $pubElapsed), $pubElapsed)
} else {
  Say "(skipped: -PublishN 0)"
}

Say ""
Say "## 2b. drain the published backlog (steady-state turns per second on one node)"
if ($PublishN -gt 0) {
  # XINFO GROUPS over RESP2 prints flat key/value lines (name, workers, consumers,
  # N, pending, N, ...), so pair them up instead of matching key names — the
  # header word "pending" would otherwise be parsed as the value.
  function GroupState {
    $lines = @(docker exec $RedisContainer redis-cli XINFO GROUPS stream:inbound)
    $map = @{}
    for ($i = 0; $i + 1 -lt $lines.Count; $i += 2) { $map[[string]$lines[$i]] = [string]$lines[$i + 1] }
    return [pscustomobject]@{ Pending = [int]$map['pending']; Lag = [int]$map['lag'] }
  }

  $drainStart = Get-Date
  $cap = 900
  while (((Get-Date) - $drainStart).TotalSeconds -lt $cap) {
    $st = GroupState
    if ($st.Pending -eq 0 -and $st.Lag -eq 0) { break }
    Start-Sleep -Seconds 1
  }
  $drainSeconds = ((Get-Date) - $drainStart).TotalSeconds
  Say ("drained {0} messages in {1:N1}s -> {2:N2} turns/s sustained on one node (16 concurrent turns)" -f $PublishN, $drainSeconds, ($PublishN / $drainSeconds))
  $r1 = RedisTotal; $q1 = MySQLQuestions
  Say ("datastore during drain: redis {0:N0} cmd/s, mysql {1:N0} q/s" -f (($r1 - $r0) / $drainSeconds), (($q1 - $q0) / $drainSeconds))
} else {
  Say "(skipped: -PublishN 0)"
}

Say ""
Say "## 3. full-turn load (real model, $TurnN turns at concurrency $TurnC)"
$r2 = RedisTotal; $q2 = MySQLQuestions; $t1 = Get-Date
$outFile = Join-Path $env:TEMP "trpc-capacity-turn.txt"
$proc = Start-Process -FilePath $exe -PassThru -NoNewWindow -RedirectStandardOutput $outFile `
  -ArgumentList @("-base", $Base, "-tenant", $Tenant, "-agent", $Agent, "-mode", "turn",
                  "-n", "$TurnN", "-c", "$TurnC", "-timeout", "6m")
$stats = @()
while (-not $proc.HasExited) {
  $stats += (docker stats --no-stream --format "{{.Name}} cpu={{.CPUPerc}} mem={{.MemUsage}}" $BackendContainer)
  Start-Sleep -Seconds 3
}
$proc.WaitForExit()
$turnElapsed = ((Get-Date) - $t1).TotalSeconds
$r3 = RedisTotal; $q3 = MySQLQuestions
Say ((Get-Content $outFile -Raw).Trim())
Say ("datastore during turns: redis {0:N0} cmd/s, mysql {1:N0} q/s (over {2:N1}s)" -f (($r3 - $r2) / $turnElapsed), (($q3 - $q2) / $turnElapsed), $turnElapsed)
Say "backend container samples:"
$stats | ForEach-Object { Say "  $_" }

Say ""
Say "## 4. turn latency percentiles from the platform's own histogram (last 15m)"
foreach ($q in @(
    'histogram_quantile(0.50, sum(rate(platform_agent_run_duration_seconds_bucket[15m])) by (le))',
    'histogram_quantile(0.90, sum(rate(platform_agent_run_duration_seconds_bucket[15m])) by (le))',
    'histogram_quantile(0.99, sum(rate(platform_agent_run_duration_seconds_bucket[15m])) by (le))',
    'sum(rate(platform_inbound_messages_total[15m]))',
    'sum(rate(platform_outbound_messages_total[15m]))',
    'sum(increase(platform_token_usage_total[15m]))')) {
  $resp = curl.exe -s --get --data-urlencode "query=$q" "http://127.0.0.1:9090/api/v1/query" | ConvertFrom-Json
  $val = $resp.data.result | Select-Object -First 1 | ForEach-Object { $_.value[1] }
  if (-not $val) { $val = "n/a" }
  Say ("{0,-110} = {1}" -f $q, $val)
}
