#!/usr/bin/env python3
"""Managed local Compose implementation; driven by `just managed-*` recipes.

One explicit local Compose project; never discovers or mutates other stacks.
Private state is generated by scripts/compose-managed-config.py on first `up`.
"""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import urllib.request
import time
import tempfile
import shutil
import urllib.error
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = ROOT / 'scripts/compose-managed-config.py'
DEFAULT_STATE = Path.home() / '.local/share/trpc-agent-service/managed-local'
REVIEW_STATE = Path.home() / '.local/share/trpc-agent-service/managed-review'
REVIEW_PROJECT = 'trpc-agent-review'
REVIEW_PORTS = {'web': 24000, 'control': 29080, 'gateway': 29090, 'gateway_admin': 29091, 'worker': 29083}
REVIEW_OVERLAY = ROOT / 'deploy/compose/compose.review.yaml'
CHANNEL_LAB_IMAGE = 'trpc-agent-service/channel-lab:managed-local'
WORKSPACE_WORKER_IMAGE = 'trpc-agent-service/agent-worker-workspace:managed-local'
WORKSPACE_SECCOMP_FILE = ROOT / 'deploy/compose/workspace/seccomp.json'
CHANNEL_LAB_URL = 'http://127.0.0.1:18090'
REVIEW_DOCS_URL = 'https://jfsas.github.io/trpc-agent-service/docs/'
FILES = [ROOT / 'deploy/compose' / name for name in (
    'compose.yaml', 'compose.local.yaml', 'compose.worker-v1.yaml', 'compose.data-backends.yaml')]


def run(command, *, capture=False, env=None):
    if len(command)>2 and list(command[:2])==['docker','compose']:
        index=command.index('--env-file')
        state=Path(command[index+1]).parent
        env={**os.environ, **read_env(state)}
    p = subprocess.run([str(x) for x in command], cwd=ROOT, text=True,
                       stdout=subprocess.PIPE if capture else None,
                       stderr=subprocess.PIPE if capture else None, env=env)
    if p.returncode:
        # Captured tools may expand private config: do not echo their output.
        raise RuntimeError(f'{Path(str(command[0])).name} failed exit={p.returncode}')
    return p.stdout if capture else ''


def read_env(state):
    result = {}
    for line in (state/'compose.env').read_text().splitlines():
        if not line or line.startswith('#'): continue
        key, value = line.split('=', 1)
        # Generated values are unquoted and contain no newlines or interpolation.
        result[key] = value
    return result


def stack_files(review):
    return [*FILES, REVIEW_OVERLAY] if review else list(FILES)


def remove_project(project):
    """Remove every container, volume and network one Compose project owns.

    Driven by Compose labels rather than `compose down`, so a reset still works
    after the private state that named those volumes has been archived.
    """
    def owned(kind, *extra):
        return run(['docker', *kind, '-q',
                    '--filter', 'label=com.docker.compose.project='+project], capture=True).split()
    containers = owned(('ps', '-a'))
    if containers: run(['docker', 'rm', '-f', *containers])
    volumes = owned(('volume', 'ls'))
    if volumes: run(['docker', 'volume', 'rm', '-f', *volumes])
    networks = owned(('network', 'ls'))
    if networks: run(['docker', 'network', 'rm', *networks])
    print('DEMO_RESET=REMOVED project=' + project + ' containers=' + str(len(containers))
          + ' volumes=' + str(len(volumes)) + ' networks=' + str(len(networks)))


def discard_state(state):
    """Delete the previous private state; the next run regenerates it.

    Refuses any path shallow enough to be a home directory, a volume root or
    the filesystem root, so a mistyped --state-dir cannot erase a broad tree.
    """
    if not state.exists(): return
    if state == Path(state.anchor) or state == Path.home() or len(state.parts) < 3:
        raise RuntimeError('refusing to delete an unexpected state directory: ' + str(state))
    shutil.rmtree(state)
    print('DEMO_RESET=DISCARDED ' + str(state))


def grant_tenants(state, review, tenants):
    """Authorize tenants in the platform catalog, then repin and restart the pair.

    The catalog feeds the release contract digest, so Control and Worker are
    recreated together; no other service depends on the granted scope.
    """
    command = [sys.executable, GENERATOR, 'grant', '--state-dir', state]
    for tenant in tenants: command += ['--tenant-id', tenant]
    # This entry is for an unused local stack; don't switch active deployments.
    run(command)
    values = read_env(state)
    pin(state, values)
    run(compose(state, values, review)+['up','-d','--no-deps','--force-recreate','control-api','agent-worker'])
    ready(values)
    return read_env(state)


def _columns(text):
    """Terminal width, so CJK labels line up with ASCII ones."""
    return sum(2 if unicodedata.east_asian_width(ch) in 'WF' else 1 for ch in text)


def _pad(text, width):
    return text + ' ' * max(1, width - _columns(text))


def welcome(state, values):
    """Human-facing summary that ends a successful `just demo` run."""
    try:
        credentials = json.loads((state/'review-credentials.json').read_text())
    except (OSError, ValueError):
        credentials = {}
    owner = credentials.get('owner') or {}
    admin = credentials.get('admin') or {}
    accent = not sys.stdout.isatty()
    def tint(text, code):
        return text if accent else '\033[' + code + 'm' + text + '\033[0m'
    def row(label, value):
        print('   ' + tint(label + ' ' * max(1, 14 - _columns(label)), '2') + value)
    def bar(left, fill, label=''):
        head = left + fill + ((' ' + label + ' ') if label else '') + fill * 2
        return tint(head + fill * max(0, 60 - _columns(head)), '36')
    web = 'http://127.0.0.1:' + str(values.get('WEB_HTTP_PORT', '24000'))
    print()
    print(bar('╭', '─', 'Agent tRPC · 评审演示环境已就绪'))
    row('管理控制台', tint(web, '1;36'))
    row('帮助文档', tint(os.environ.get('DOCS_SITE_URL', REVIEW_DOCS_URL), '36'))
    row('模拟 IM', tint(CHANNEL_LAB_URL, '36'))
    row('Gateway 管理', tint('http://127.0.0.1:' + str(values.get('GATEWAY_ADMIN_PORT', '29091')), '36'))
    print()
    row('租户账号', tint(_pad(str(owner.get('username', '(见凭据文件)')), 14), '1') + '评测建议使用')
    row('租户密码', tint(str(owner.get('password', '(见凭据文件)')), '1'))
    row('管理员账号', tint(_pad(str(admin.get('username', '(见凭据文件)')), 14), '1') + '平台管理')
    row('管理员密码', tint(str(admin.get('password', '(见凭据文件)')), '1'))
    print()
    row('演示 Agent', 'Demo Assistant · 已发布 ' + str(credentials.get('deployment_revision', 1)) + ' 个版本')
    row('运行模型', str(credentials.get('model', 'lab-echo')) + ' · ' + str(credentials.get('model_source', 'channel-lab')))
    print()
    row('停止环境', 'just demo-stop         保留私有 state 与命名卷')
    row('查看状态', 'just demo-status       复检容器与就绪探针')
    row('凭据文件', str(state/'review-credentials.json'))
    print()
    print(bar('╰', '─', '说明'))
    for line in ['Channel Lab 可以发送消息，但当前种子流程尚未执行渠道预检，',
                 'Agent 暂时不会回复。登录、控制台与帮助文档均不受影响。']:
        print(tint('   ' + line, '2'))
    print()


def compose(state, values, review=False):
    project = values.get('COMPOSE_PROJECT_NAME', 'trpc-agent-managed-local')
    if project in ('trpc-agent-latest', 'channel-lab-dev'):
        raise RuntimeError('select an independent managed project')
    cmd = ['docker', 'compose', '--project-name', project, '--env-file', state/'compose.env']
    for path in stack_files(review): cmd.extend(['-f', path])
    return cmd


def pin(state, values):
    names = ['CONTROL_PLATFORM_BACKEND_CATALOG_SHA256', 'CONTROL_PLATFORM_BACKEND_TARGETS_SHA256']
    environment = os.environ.copy()
    cmd = ['docker', 'run', '--rm']
    for name in names:
        environment[name] = values[name]
        cmd.extend(['-e', name])
    cmd.extend([values['CONTROL_API_IMAGE'], '--print-deployment-contract-digest'])
    digest = run(cmd, capture=True, env=environment).strip()
    if not re.fullmatch(r'sha256:[a-f0-9]{64}', digest):
        raise RuntimeError('Control returned invalid contract digest')
    run([sys.executable, GENERATOR, 'pin', '--state-dir', state, '--digest', digest])


def ready(values):
    endpoints = {
        'control': f"http://127.0.0.1:{values.get('CONTROL_API_HTTP_PORT','28080')}/healthz",
        'gateway': f"http://127.0.0.1:{values.get('GATEWAY_ADMIN_PORT','28091')}/readyz",
        'worker': f"http://127.0.0.1:{values.get('WORKER_ADMIN_PORT','28083')}/readyz",
        'web': f"http://127.0.0.1:{values.get('WEB_HTTP_PORT','23000')}/",
    }
    pending = dict(endpoints); deadline = time.monotonic()+180
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    while pending and time.monotonic() < deadline:
        for name, url in list(pending.items()):
            try:
                with opener.open(url, timeout=3) as response:
                    if response.status in (200,204): del pending[name]
            except urllib.error.HTTPError as error: error.close()
            except OSError: pass
        if pending: time.sleep(2)
    if pending: raise RuntimeError('HTTP readiness failed: '+','.join(pending))
    print('APPLICATION_HTTP_READY=PASS control gateway worker web')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('action', choices=['up','demo','reset','status','stop','grant','restart-backends','config'])
    p.add_argument('--state-dir', type=Path)
    p.add_argument('--project')
    p.add_argument('--tenant-id', action='append')
    p.add_argument('--skip-build', action='store_true', help='use already-built images explicitly')
    p.add_argument('--review', action='store_true', help='target the reviewer demo stack')
    args = p.parse_args()
    review = args.review or args.action in ('demo', 'reset')
    if review: os.environ.setdefault('DOCS_SITE_URL', REVIEW_DOCS_URL)
    if review:
        os.environ.setdefault('WORKSPACE_WORKER_IMAGE', WORKSPACE_WORKER_IMAGE)
        os.environ['WORKSPACE_SECCOMP_FILE'] = str(WORKSPACE_SECCOMP_FILE)
    args.project = args.project or (REVIEW_PROJECT if review else 'trpc-agent-managed-local')
    state = (args.state_dir or (REVIEW_STATE if review else DEFAULT_STATE)).expanduser().resolve()
    if args.action == 'reset':
        # Only an explicit reset destroys the owned stack and its data; `demo`
        # rebuilds and restarts while keeping volumes and private state.
        remove_project(args.project)
        discard_state(state)
        args.action = 'demo'
    if args.action in ('up', 'demo') and not (state/'compose.env').exists():
        cmd = [sys.executable, GENERATOR, 'init', '--state-dir', state, '--project', args.project]
        if review:
            for name, port in REVIEW_PORTS.items(): cmd += ['--'+name.replace('_','-')+'-port', str(port)]
        run(cmd)
    if not (state/'compose.env').exists(): raise RuntimeError('run up to initialize this state first')
    values=read_env(state); dc=compose(state, values, review)
    if args.action in ('up', 'demo'):
        # Build independent release images; -f overlays are always the complete stack.
        if not args.skip_build:
            # Reuse the host Go module cache; no credentials or repo files enter
            # the runtime image context, only the cross-built executable.
            arch = run(['docker','info','--format','{{.Architecture}}'],capture=True).strip()
            arch = {'aarch64':'arm64','x86_64':'amd64'}.get(arch,arch)
            if arch not in ('arm64','amd64'): raise RuntimeError('unsupported Docker architecture')
            environment=os.environ.copy()
            environment.update(CGO_ENABLED='0',GOOS='linux',GOARCH=arch)
            for service, package in [('CONTROL_API','control-api'),('CHANNEL_GATEWAY','channel-gateway'),('AGENT_WORKER','agent-worker')]:
                with tempfile.TemporaryDirectory(prefix='managed-image-') as build_dir:
                    run(['go','build','-trimpath','-ldflags=-s -w','-o',Path(build_dir)/'binary',
                         './services/'+package+'/cmd/'+package],env=environment)
                    shutil.copyfile(ROOT/'deploy/compose/Dockerfile.runtime-managed',Path(build_dir)/'Dockerfile')
                    run(['docker','build','-t',values[service+'_IMAGE'],build_dir])
            run(['docker','build','-t',values.get('WEB_IMAGE','trpc-agent-service/web:managed-local'),
                 '--build-arg','RUNTIME_API_BASE=http://channel-gateway:8090',
                 '-f','deploy/compose/Dockerfile.web-managed','.'])
            run(['docker','build','-t',values.get('BACKEND_TOOLS_IMAGE','trpc-agent-service/backend-tools:managed-local'),
                 '-f','deploy/compose/Dockerfile.backend-tools','deploy/compose'])
            if review:
                run(['docker','build','-t',CHANNEL_LAB_IMAGE,'-f','tools/channel-lab/Dockerfile','tools/channel-lab'])
                # The workspace Worker needs its own base image (bash + bwrap);
                # it reuses the same cross-built binary as the distroless one.
                with tempfile.TemporaryDirectory(prefix='workspace-image-') as build_dir:
                    run(['go','build','-trimpath','-ldflags=-s -w','-o',Path(build_dir)/'binary',
                         './services/agent-worker/cmd/agent-worker'],env=environment)
                    shutil.copyfile(ROOT/'deploy/compose/Dockerfile.worker-workspace',Path(build_dir)/'Dockerfile')
                    run(['docker','build','-t',WORKSPACE_WORKER_IMAGE,build_dir])
        pin(state,values); values=read_env(state); dc=compose(state,values,review)
        acl=[sys.executable,ROOT/'deploy/compose/data-backends/backendctl.py','redis-acl']
        for role in ['admin','memory','session']:
            acl += ['--'+role+'-password-file',state/'secrets'/('redis_'+role)]
        acl += ['--output',state/'redis/users.acl']; run(acl)
        run(dc+['config','--quiet'])
        run(dc+['up','-d','--no-build','--wait','--wait-timeout','240'])
        ready(values)
        if review:
            # Grant every demo tenant the managed backends before anything is
            # published: the catalog is part of the release contract digest, so
            # a later grant would invalidate already published revisions.
            credentials_path = state/'review-credentials.json'
            credentials = {}
            if credentials_path.exists():
                try: credentials = json.loads(credentials_path.read_text())
                except (OSError, ValueError): credentials = {}
            seed = [sys.executable, ROOT/'scripts/demo-seed.py', '--state-dir', str(state),
                    '--control-url', 'http://127.0.0.1:'+str(values.get('CONTROL_API_HTTP_PORT','29080'))]
            if credentials.get('seeded'):
                print('DEMO_SEED=SKIP already seeded')
            else:
                # A failed publish must be resumable: the tenant already exists,
                # so only the missing publication steps are retried.
                if not credentials.get('tenant_id'):
                    run(seed+['--phase','tenant'])
                    credentials = json.loads(credentials_path.read_text())
                values = grant_tenants(state, review, [credentials['tenant_id']])
                run(seed+['--phase','publish','--lab-url',CHANNEL_LAB_URL])
            welcome(state, values)
        else:
            print('MANAGED_STACK=READY project='+values.get('COMPOSE_PROJECT_NAME',args.project))
            print('PRIVATE_CONFIG='+str(state))
            print('EXTERNAL_MODEL=NOT_PROVISIONED_BY_STARTUP IM_BINDING=NOT_PROVISIONED_BY_STARTUP')
    elif args.action=='grant':
        if not args.tenant_id: raise RuntimeError('grant requires explicit --tenant-id')
        grant_tenants(state, review, args.tenant_id); print('CATALOG_GRANT_PIN=PASS')
    elif args.action=='status':
        run(dc+['ps']); ready(values)
    elif args.action=='config': run(dc+['config','--quiet']); print('COMPOSE_CONFIG=PASS')
    elif args.action=='stop': run(dc+['stop']); print('VOLUMES_PRESERVED=true')
    elif args.action=='restart-backends':
        run(dc+['restart','postgres','redis','qdrant','minio'])
        run(dc+['exec','-T','backend-tools','sh','/tooling/health-all.sh'])
        print('BACKEND_RESTART=PASS volumes_preserved=true')


if __name__=='__main__':
    try: main()
    except (OSError, ValueError, KeyError, RuntimeError) as error:
        print('MANAGED_STACK=FAIL '+str(error), file=sys.stderr); sys.exit(1)
