// Package minio is the object-store adapter: a minimal, path-style S3 client
// with hand-written SigV4 signing.
//
// Why hand-written instead of the vendor SDK: this platform needs five calls
// (ensure bucket, put, get, delete, head) on small, operator-sized objects,
// and the dependency budget is a reviewed artefact of this repository (see
// docs/依赖基线.txt). A signing bug is not silent here — the real MinIO
// container in the E2E rejects the request with a signed error — which makes
// the trade acceptable and measurable.
//
// Object keys are generated by the platform (tenant/app/doc/generation/…),
// never by a user, and are restricted to a conservative charset by
// ValidateKey, so canonicalisation never has to guess.
package minio

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"
)

// Client is one bucket on one MinIO (or S3-compatible) endpoint.
type Client struct {
	endpoint  *url.URL
	region    string
	accessKey string
	secretKey string
	bucket    string
	http      *http.Client
}

const (
	emptyPayloadHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
	maxObjectBytes   = 32 << 20
)

// New builds a client. endpoint is the service root (http://minio:9000).
func New(endpoint, accessKey, secretKey, region, bucket string) (*Client, error) {
	u, err := url.Parse(strings.TrimRight(endpoint, "/"))
	if err != nil {
		return nil, fmt.Errorf("minio: endpoint: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return nil, fmt.Errorf("minio: endpoint %q needs scheme and host", endpoint)
	}
	if accessKey == "" || secretKey == "" {
		return nil, fmt.Errorf("minio: credentials are required")
	}
	if bucket == "" || !keyCharset.MatchString(bucket) {
		return nil, fmt.Errorf("minio: bucket name %q is not in the supported charset", bucket)
	}
	if region == "" {
		region = "us-east-1"
	}
	return &Client{
		endpoint:  u,
		region:    region,
		accessKey: accessKey,
		secretKey: secretKey,
		bucket:    bucket,
		http:      &http.Client{Timeout: 30 * time.Second},
	}, nil
}

var keyCharset = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9/_.-]*$`)

// ValidateKey enforces the charset object keys are drawn from. It is called
// on every operation: a key that reached the signer unchecked would be
// canonicalised under different rules than the server applies, and the two
// spellings of one key is exactly how a stale object survives a cleanup.
func ValidateKey(key string) error {
	if key == "" || len(key) > 512 {
		return fmt.Errorf("minio: object key length %d is out of range", len(key))
	}
	if !keyCharset.MatchString(key) || strings.Contains(key, "//") {
		return fmt.Errorf("minio: object key %q is not in the supported charset", key)
	}
	return nil
}

// EnsureBucket creates the bucket if it does not exist. A bucket owned by
// this account (409 BucketAlreadyOwnedByYou) is success; one owned by someone
// else is a hard error, because writing into it would be a cross-account
// surprise.
func (c *Client) EnsureBucket(ctx context.Context) error {
	status, body, err := c.do(ctx, http.MethodPut, "/"+c.bucket, nil, "")
	if err != nil {
		return fmt.Errorf("minio: ensure bucket: %w", err)
	}
	switch {
	case status == http.StatusOK:
		return nil
	case status == http.StatusConflict:
		code := s3ErrorCode(body)
		if code == "BucketAlreadyOwnedByYou" || code == "BucketAlreadyExists" {
			// Either this account created it before, or the deployment is
			// pointed at a shared bucket — the latter is the operator's
			// decision and MinIO has already authorized the call.
			return nil
		}
		return fmt.Errorf("minio: ensure bucket: conflict: %s", code)
	case status == http.StatusForbidden:
		return fmt.Errorf("minio: ensure bucket: access denied for %q", c.bucket)
	default:
		return fmt.Errorf("minio: ensure bucket: status %d: %s", status, s3ErrorMessage(body))
	}
}

// Put writes an object and fails unless the store confirms it: a "staged"
// document row whose bytes never landed must not become indexable.
func (c *Client) Put(ctx context.Context, key string, data []byte, contentType string) error {
	if err := ValidateKey(key); err != nil {
		return err
	}
	if contentType == "" {
		contentType = "application/octet-stream"
	}
	status, body, err := c.do(ctx, http.MethodPut, "/"+c.bucket+"/"+key, data, contentType)
	if err != nil {
		return fmt.Errorf("minio: put %s: %w", key, err)
	}
	if status != http.StatusOK {
		return fmt.Errorf("minio: put %s: status %d: %s", key, status, s3ErrorMessage(body))
	}
	return nil
}

// Get reads an object whole. Objects in this platform are operator-sized
// (documents, artifacts), and maxObjectBytes is the same ceiling the upload
// path enforces, so streaming would add code without changing behaviour.
func (c *Client) Get(ctx context.Context, key string) ([]byte, error) {
	if err := ValidateKey(key); err != nil {
		return nil, err
	}
	status, body, err := c.do(ctx, http.MethodGet, "/"+c.bucket+"/"+key, nil, "")
	if err != nil {
		return nil, fmt.Errorf("minio: get %s: %w", key, err)
	}
	if status == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if status != http.StatusOK {
		return nil, fmt.Errorf("minio: get %s: status %d: %s", key, status, s3ErrorMessage(body))
	}
	if len(body) > maxObjectBytes {
		return nil, fmt.Errorf("minio: get %s: object exceeds %d bytes", key, maxObjectBytes)
	}
	return body, nil
}

// Delete removes an object. Deleting an absent key is success (S3 semantics):
// a cleanup job that ran twice must not fail on its second run.
func (c *Client) Delete(ctx context.Context, key string) error {
	if err := ValidateKey(key); err != nil {
		return err
	}
	status, body, err := c.do(ctx, http.MethodDelete, "/"+c.bucket+"/"+key, nil, "")
	if err != nil {
		return fmt.Errorf("minio: delete %s: %w", key, err)
	}
	if status != http.StatusNoContent && status != http.StatusOK && status != http.StatusNotFound {
		return fmt.Errorf("minio: delete %s: status %d: %s", key, status, s3ErrorMessage(body))
	}
	return nil
}

// Exists reports whether an object is present.
func (c *Client) Exists(ctx context.Context, key string) (bool, error) {
	if err := ValidateKey(key); err != nil {
		return false, err
	}
	status, _, err := c.do(ctx, http.MethodHead, "/"+c.bucket+"/"+key, nil, "")
	if err != nil {
		return false, fmt.Errorf("minio: head %s: %w", key, err)
	}
	switch status {
	case http.StatusOK:
		return true, nil
	case http.StatusNotFound:
		return false, nil
	default:
		return false, fmt.Errorf("minio: head %s: status %d", key, status)
	}
}

// ErrNotFound is returned by Get for a missing object.
var ErrNotFound = fmt.Errorf("minio: object not found")

// do signs and performs one request. The response body is read whole (bounded
// for GET; error bodies are tiny) so callers can inspect S3 error codes.
func (c *Client) do(ctx context.Context, method, path string, payload []byte, contentType string) (int, []byte, error) {
	if len(payload) > maxObjectBytes {
		return 0, nil, fmt.Errorf("payload exceeds %d bytes", maxObjectBytes)
	}
	payloadHash := emptyPayloadHash
	if len(payload) > 0 {
		sum := sha256.Sum256(payload)
		payloadHash = hex.EncodeToString(sum[:])
	}

	now := time.Now().UTC()
	amzDate := now.Format("20060102T150405Z")
	dateStamp := now.Format("20060102")

	host := c.endpoint.Host
	canonicalHeaders := "host:" + host + "\n" +
		"x-amz-content-sha256:" + payloadHash + "\n" +
		"x-amz-date:" + amzDate + "\n"
	signedHeaders := "host;x-amz-content-sha256;x-amz-date"

	canonicalRequest := strings.Join([]string{
		method,
		canonicalURI(path),
		"", // no query parameters in this client
		canonicalHeaders,
		signedHeaders,
		payloadHash,
	}, "\n")

	scope := dateStamp + "/" + c.region + "/s3/aws4_request"
	stringToSign := strings.Join([]string{
		"AWS4-HMAC-SHA256",
		amzDate,
		scope,
		hexSHA256([]byte(canonicalRequest)),
	}, "\n")

	signingKey := hmacSHA256(
		hmacSHA256(
			hmacSHA256(
				hmacSHA256([]byte("AWS4"+c.secretKey), []byte(dateStamp)),
				[]byte(c.region)),
			[]byte("s3")),
		[]byte("aws4_request"))
	signature := hex.EncodeToString(hmacSHA256(signingKey, []byte(stringToSign)))

	req, err := http.NewRequestWithContext(ctx, method, c.endpoint.String()+canonicalURI(path), bytes.NewReader(payload))
	if err != nil {
		return 0, nil, err
	}
	req.Host = host
	req.Header.Set("X-Amz-Date", amzDate)
	req.Header.Set("X-Amz-Content-Sha256", payloadHash)
	if contentType != "" && len(payload) > 0 {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Authorization", fmt.Sprintf(
		"AWS4-HMAC-SHA256 Credential=%s/%s, SignedHeaders=%s, Signature=%s",
		c.accessKey, scope, signedHeaders, signature))

	resp, err := c.http.Do(req)
	if err != nil {
		return 0, nil, err
	}
	defer resp.Body.Close()
	limit := int64(4 << 20)
	if method == http.MethodGet && resp.StatusCode == http.StatusOK {
		limit = maxObjectBytes + 1
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, limit))
	if err != nil {
		return resp.StatusCode, nil, err
	}
	return resp.StatusCode, body, nil
}

// canonicalURI encodes each path segment per RFC 3986 while keeping the
// separator: the same spelling the server will reconstruct.
func canonicalURI(path string) string {
	segments := strings.Split(path, "/")
	for i, s := range segments {
		segments[i] = uriEncode(s)
	}
	uri := strings.Join(segments, "/")
	if uri == "" {
		uri = "/"
	}
	return uri
}

func uriEncode(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		ch := s[i]
		switch {
		case ch >= 'A' && ch <= 'Z', ch >= 'a' && ch <= 'z', ch >= '0' && ch <= '9',
			ch == '-', ch == '_', ch == '.', ch == '~':
			b.WriteByte(ch)
		default:
			fmt.Fprintf(&b, "%%%02X", ch)
		}
	}
	return b.String()
}

func hexSHA256(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func hmacSHA256(key, data []byte) []byte {
	h := hmac.New(sha256.New, key)
	h.Write(data)
	return h.Sum(nil)
}

func s3ErrorCode(body []byte) string {
	var e struct {
		Code string `xml:"Code"`
	}
	_ = xml.Unmarshal(body, &e)
	return e.Code
}

func s3ErrorMessage(body []byte) string {
	var e struct {
		Code    string `xml:"Code"`
		Message string `xml:"Message"`
	}
	if err := xml.Unmarshal(body, &e); err != nil || e.Code == "" {
		return strings.TrimSpace(string(body[:min(len(body), 200)]))
	}
	return e.Code + ": " + e.Message
}
