import type { AgentVersion } from "../lib/control-api";
import type { ProfileRevision } from "../lib/runtime-profile-api";
import type { Deployment, DeploymentInput, DeploymentReport, DeploymentRevision } from "../lib/deployment-api";
import manifest from "../../api/schemas/deployment/v1/examples/valid/runtime-manifest-view.json";

export const deployment: Deployment = { id: "d", tenant_id: "t", name: "研究助手部署", description: "多工具发布", metadata_revision: 1, latest_revision_number: null, created_by: "u", created_at: "2026-09-05", updated_at: "2026-09-05" };
export const input: DeploymentInput = { schema_version: "v1", agent: { agent_id: "a", version_number: 3 }, profile: { profile_id: "p", revision_number: 2 } };
export const validReport: DeploymentReport = { valid: true, compiler_version: "deployment-compiler-v1", platform_contract_digest: "sha256:contract", diagnostics: [] };
export const invalidReport: DeploymentReport = { ...validReport, valid: false, diagnostics: [{ code: "DEPLOYMENT_RESOURCE_MISSING", severity: "error", source: "agent", path: "/requirements/tools/search", category: "tools", name: "search", node_id: null, message: "ProfileRevision is missing the same-name tool resource" }] };
export const agentVersion: AgentVersion = { id: "av", tenant_id: "t", agent_id: "a", version_number: 3, source_draft_revision: 2, schema_version: "v1", spec_digest: "sha256:agent", published_by: "u", published_at: "2026-09-05", spec: { schema_version: "v1", root: "researcher", requirements: { models: { primary: { capabilities: ["chat", "tool_call"] } }, tools: { search: { capability: "web.search" } }, knowledge: { docs: { capability: "knowledge.search" } } }, nodes: { researcher: { kind: "llm", instruction: "Research", model_slot: "primary", tool_slots: ["search"], knowledge_slots: ["docs"] } } } };
export const profileRevision: ProfileRevision = { id: "pr", tenant_id: "t", profile_id: "p", revision_number: 2, source_draft_revision: 2, schema_version: "v1", spec_digest: "sha256:profile", published_by: "u", published_at: "2026-09-05", credential_protocol_version: "v1", config: { models: { primary: { kind: "openai_compatible", base_url: "https://model.example.test/v1", model: "chat", capabilities: ["chat", "tool_call"] } }, tools: { search: { kind: "mcp_streamable_http", tool_name: "search_web", capability: "web.search" } }, knowledge: { docs: { kind: "qdrant_openai" } }, storage: { session: { kind: "postgres_state" } } } };
export const revision: DeploymentRevision = { id: "dr", tenant_id: "t", deployment_id: "d", revision_number: 1, schema_version: "v1", agent_id: "a", agent_version_number: 3, profile_id: "p", profile_revision_number: 2, input, input_digest: "sha256:input", manifest_id: "mf", manifest_digest: "sha256:manifest", manifest_view: manifest, published_by: "u", published_at: "2026-09-05" };
