apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trpc-agent
resources:
  - ../../base
patches:
  - path: bootstrap-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: trpc-agent-service
    newName: trpc-agent-service
    newTag: kubernetes-demo
